### ISSUE TITLE
Warning for flutter 3.0.0

### ISSUE THREAD

**Issue by chatchit-project** [ZEGOCLOUD/zego_uikit_prebuilt_call_flutter#1]
: Warning: Operand of null-aware operation '??' has type 'int' which excludes null. ZIMCommonData.mediaUploadingProgressMap[progressID ?? 0];
<img width="1032" alt="Screen Shot 2022-11-09 at 14 49 33" src="https://user-images.githubusercontent.com/117077712/200769905-0332d327-8a69-4d59-8ab3-8b7f86fa7c6a.png">

**Comment by yoer** [comment]
but for WidgetsBinding.instance?.addPostFrameCallback, this warning will always exist until we decide to not support flutter 2.+ version anymore
