### ISSUE TITLE
Error: The argument type 'ImmutableBuffer' can't be assigned to the parameter type 'Image'.

### ISSUE THREAD

**Issue by tasaddaq-hussain** [ZEGOCLOUD/zego_uikit_prebuilt_call_flutter#13]
I am facing this error when i integrated "zego_uikit_prebuilt_call" package =>(https://pub.dev/packages/zego_uikit_prebuilt_call).

Error messages: 
: Error: The argument type 'ImmutableBuffer' can't be assigned to the parameter type 'Image'.
resource_image_provider.dart:61
 - 'ImmutableBuffer' is from 'dart:ui'.
 - 'Image' is from 'dart:ui'.
    return decode(buffer);
                  ^
: Error: A value of type 'void' can't be returned from an async function with return type 'Future<Codec>'.
resource_image_provider.dart:61

 - 'Future' is from 'dart:async'.
 - 'Codec' is from 'dart:ui'.
    return decode(buffer);
                 ^

This is result of from: 'flutter doctor'
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.7.6, on Ubuntu 22.04.2 LTS 5.19.0-43-generic, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2022.2)
[✓] Android Studio
[✓] VS Code (version 1.79.1)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!

**Comment by tasaddaq-hussain** [comment]
any update please!

**Comment by yoer** [comment]
Could you provide a detailed code stack trace for the error messages? I couldn't find which code segment is causing the errors based on the information you provided.

**Comment by tasaddaq-hussain** [comment]
error is solved after flutter upgrade into 3.10.5
