### ISSUE TITLE
Incompatible versions of packages used.

### ISSUE THREAD

**Issue by Ahtsham0715** [ZEGOCLOUD/zego_uikit_prebuilt_call_flutter#14]
Please upgrade packages versions used in your pubspec.yaml file. there are multiple issues in flutter 3.10 with this package.

1- AppData/Local/Pub/Cache/hosted/pub.dev/flutter_screenutil_zego-5.6.0/lib/src/screen_util.dart:58:5: Error: 'FlutterWindow' isn't a type.
    FlutterWindow? window,

**Comment by yoer** [comment]
flutter_screenutil_zego is deprecated, plz upgrade latest [https://pub.dev/packages/zego_uikit_prebuilt_call](zego_uikit_prebuilt_call) or use [https://pub.dev/packages/flutter_screenutil](flutter_screenutil)
