### ISSUE TITLE
dependency conflict

### ISSUE THREAD

**Issue by manumathew17** [ZEGOCLOUD/zego_uikit_prebuilt_call_flutter#16]
Because zego_uikit_prebuilt_call 3.10.5 depends on http ^0.13.4 and no versions of zego_uikit_prebuilt_call match >3.10.5 <4.0.0, zego_uikit_prebuilt_call ^3.10.5 requires http ^0.13.4.
So, because my app depends on both http ^1.1.0 and zego_uikit_prebuilt_call ^3.10.5, version solving failed.

why are you using outdated packages?

**Comment by yoer** [comment]
you can update latest version v3.10.6 and try again

**Comment by manumathew17** [comment]
still getting the same error
Resolving dependencies...
Because zego_uikit_prebuilt_call >=3.10.5 depends on audioplayers ^4.1.0 which depends on http ^0.13.5, zego_uikit_prebuilt_call >=3.10.5 requires http ^0.13.5.
So, because lively_studio depends on both http ^1.1.0 and zego_uikit_prebuilt_call ^3.10.5, version solving failed.
Process finished with exit code 1

dependencies are
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  sizer: ^2.0.15
  shared_preferences: ^2.2.0
  google_fonts: ^4.0.4
  go_router: ^9.0.3
  http: ^1.1.0
  email_validator: ^2.1.17
  zego_uikit_prebuilt_call: ^3.10.5
  zego_uikit_signaling_plugin: ^2.2.0

**Comment by yoer** [comment]
3.10.6 had remove http package

**Comment by yoer** [comment]
execute 'flutter pub upgrade', and check the 'zego_uikit_prebuilt_call' version

**Comment by yoer** [comment]
Have you added camera and microphone permissions to your app's AndroidManifest.xml or Info.plist? 
Have you granted the permissions? 

You can refer to our [official website tutorial](https://docs.zegocloud.com/article/14826) or our [demo for guidance](https://github.com/ZEGOCLOUD/zego_uikit_prebuilt_call_example_flutter/tree/master/call_with_offline_invitation).
