### ISSUE TITLE
Confirm dialog text is not showing to the user

### ISSUE THREAD

**Issue by manumathew17** [ZEGOCLOUD/zego_uikit_prebuilt_call_flutter#18]
The confirm to exit dialog title and message is not showing properly

`      ..hangUpConfirmDialogInfo = ZegoHangUpConfirmDialogInfo(
            title: "Confirm?",
            message: "Do you want to exit from call?",
            cancelButtonName: "Cancel",
            confirmButtonName: "Confirm",
          )`

![image](https://github.com/ZEGOCLOUD/zego_uikit_prebuilt_call_flutter/assets/54477058/d7feba10-c675-4a9c-9879-02a367cd84c9)

**Comment by yoer** [comment]
This seems a bit odd. Is your app theme something like dark mode? 
It seems necessary to develop the style configuration of the pop-up dialog.

**Comment by yoer** [comment]
the issue has been too long without a reply, so it is closed.
