### ISSUE TITLE
Please Update the Design to match Google's Material UI 3.0 So we can use it instead of agora

### ISSUE THREAD

**Issue by Ghazanfarrajpoot** [ZEGOCLOUD/zego_uikit_prebuilt_call_flutter#2]
Please zeego, Update the UI to Material ui 3.0.

**Comment by yoer** [comment]
ok, we will think about that

**Comment by yoer** [comment]
discuss on https://github.com/ZEGOCLOUD/zego_uikit_prebuilt_call_flutter/issues/15, closed
