### ISSUE TITLE
getting these warning:

### ISSUE THREAD

**Issue by fisforfaheem** [ZEGOCLOUD/zego_uikit_prebuilt_call_flutter#21]
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/4edoc/.pub-cache/hosted/pub.dev/firebase_messaging-14.6.5/android/src/main/java/io/flutter/plugins/firebase/messaging/FlutterFirebaseMessagingPlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: /Users/4edoc/.pub-cache/hosted/pub.dev/cloud_firestore-4.8.3/android/src/main/java/io/flutter/plugins/firebase/firestore/FlutterFirebaseFirestoreMessageCodec.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: /Users/4edoc/.pub-cache/hosted/pub.dev/zego_zim-2.7.1/android/src/main/java/im/zego/zim_flutter/internal/ZIMPluginConverter.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/4edoc/.pub-cache/hosted/pub.dev/zego_zim-2.7.1/android/src/main/java/im/zego/zim_flutter/internal/ZIMPluginConverter.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/4edoc/.pub-cache/hosted/pub.dev/zego_zpns-2.4.0/android/src/main/java/im/zego/zpns_flutter/internal/ZPNsPluginMethodHandler.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: /Users/4edoc/.pub-cache/hosted/pub.dev/flutter_share-2.0.0/android/src/main/java/com/example/fluttershare/FlutterSharePlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/4edoc/.pub-cache/hosted/pub.dev/native_device_orientation-1.1.4/android/src/main/java/com/github/rmtmckenzie/native_device_orientation/NativeDeviceOrientationPlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/4edoc/.pub-cache/hosted/pub.dev/flutter_ringtone_player-3.2.0/android/src/main/java/io/inway/ringtone/player/FlutterRingtonePlayerPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/4edoc/.pub-cache/hosted/pub.dev/zego_express_engine-3.6.1/android/src/main/java/im/zego/zego_express_engine/internal/ZegoExpressEngineMethodHandler.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

**Comment by yoer** [comment]
that's another sdk's warnings, firebase, zim, zego_express
