### ISSUE TITLE
How to get better ringtone and notification sound?? for flutter 

### ISSUE THREAD

**Issue by fisforfaheem** [ZEGOCLOUD/zego_uikit_prebuilt_call_flutter#22]
cant find any soultion

**Comment by yoer** [comment]
for online notification, you can use **ringtoneConfig** and **androidNotificationConfig.sound**

**Comment by yoer** [comment]
if you talk about offline notification, you should set in [ZEGOCLOUD management console](https://console.zegocloud.com/)

that 's [document](https://docs.zegocloud.com/article/15777)

**Comment by fisforfaheem** [comment]
is there any tutorial for this notification sound and ringtone for flutter,
i am using flutter awesome notifications

**Comment by yoer** [comment]
you can see [this](https://docs.zegocloud.com/article/15777) if you mean uikit call
