### ISSUE TITLE
XCode Archive failes with Command PhaseScriptExecution failed with a nonzero exit code

### ISSUE THREAD

**Issue by msarkrish** [ZEGOCLOUD/zego_uikit_prebuilt_call_flutter#23]
Hi ZegoCloud Team,

We are using zego_uikit, zego_uikit_prebuilt_call and zego_uikit_signaling_plugin in our mobile application which is created using flutter.

In iOS while trying to take build, we are facing this **Command PhaseScriptExecution failed with a nonzero exit code**. 

While checking the log, I found that Xcode is pointing to path which doesn't exist.

![image](https://github.com/ZEGOCLOUD/zego_uikit_prebuilt_call_flutter/assets/45334931/6b49e985-9181-4600-bf15-85efeec241d3)

Any one know how to fix this issue?
 
Thanks in advance.

**Comment by yoer** [comment]
Your custom shell script [CP-User] download native dependency encountered an issue: /Users/xxx/Developer/T-EAM: no such file or directory.

**Comment by msarkrish** [comment]
Yes @yoer but that is a invalid path. I haven't mentioned this path any where in my project.
Can you help me to resolve this issue?

**Comment by yoer** [comment]
try clean build plz

**Comment by yoer** [comment]
may be try search keyword in your project?

**Comment by yoer** [comment]
have you slove this problem?

**Comment by yoer** [comment]
<img width="725" alt="image" src="https://github.com/ZEGOCLOUD/zego_uikit_prebuilt_call_flutter/assets/11307627/595d6f22-09f1-49cc-aa15-18cc76e60103">

![image](https://github.com/ZEGOCLOUD/zego_uikit_prebuilt_call_flutter/assets/11307627/d842a107-1fec-483e-bda0-cbd80808ac0e)

**Comment by yoer** [comment]
Is the path to your project containing spaces or special characters? If so, please try using a path with regular words.

**Comment by msarkrish** [comment]
@yoer I will check this and let you know

**Comment by loopstack33** [comment]
it is causing issue in  zego_express_engine also the latest zego_uikit_prebuilt_call: ^3.13.5 does not depends on latest zego_zpns 2.4.0+1 please fix that. As soon as possible can't run app on ios due to this issue.
<img width="1440" alt="dsadsad" src="https://github.com/ZEGOCLOUD/zego_uikit_prebuilt_call_flutter/assets/99548269/21208bb9-4e29-4ba8-8b08-c89a1ece2e89">

**Comment by loopstack33** [comment]
I am using Flutter 3.13.0 • channel stable
My cocoa pods version cocoapods-1.12.1
latest version of ui_kit.

**Comment by yoer** [comment]
if you not **Disable the Bitcode**, please follow this [document](https://docs.zegocloud.com/article/14826) disable it.
and not **Disable Build Libraries for Distribution,** also follow the document to disable it.

and, check you project path, does it contain any empty characters or invalid characters?

**Comment by loopstack33** [comment]
@yoer  Thank you soo much really helped me out it fixed my problem.

**Comment by msarkrish** [comment]
> Is the path to your project containing spaces or special characters? If so, please try using a path with regular words.



> if you not **Disable the Bitcode**, please follow this [document](https://docs.zegocloud.com/article/14826) disable it. OR if not **Disable Build Libraries for Distribution,** also follow the document to disable it.
> 
> and, check you **project path**, does it contain any **empty character**s or invalid characters?
> 
> After update project config or the path, try delete the "Pods" folder and "Podfile.lock" file, and then reinstall.
> 
> @loopstack33

Thank you @yoer . With the help of above mentioned 2 comments issue get resolved.

**Comment by msarkrish** [comment]
My issue and @loopstack33 issue get resolved. so I'm closing this issue.
