### ISSUE TITLE
Capture Local User Video Frames as JPEG Images in ZEGOCLOUD Flutter Plugin

### ISSUE THREAD

**Issue by azazadev** [ZEGOCLOUD/zego_uikit_prebuilt_call_flutter#24]
I would like to request confirmation and support regarding the ability of the ZEGOCLOUD Flutter plugin to capture frames from the local user's video stream as JPEG images ?  My use case involves implementing a one-to-one video call functionality while applying a custom TFLite machine learning model to each frame of the video stream

**Comment by yoer** [comment]
i'm sorry, we haven't support these callbacks
