### ISSUE TITLE
Cal invitation isn't working when app is killed

### ISSUE THREAD

**Issue by ahmedsaleh210** [ZEGOCLOUD/zego_uikit_prebuilt_call_flutter#25]
Call invitation works fine with me in background & foreground state
But terminated state not working..

**Comment by yoer** [comment]
We support offline calls. You can refer to the **Enable & Use the offline call invitation** section in the (documentation](https://docs.zegocloud.com/article/14826). If you have any questions, you can contact the technical support on the official website.

**Comment by yoer** [comment]
i'm sorry, we haven't support these callbacks
