### ISSUE TITLE
upgrade awesome_notifications

### ISSUE THREAD

**Issue by moesaid** [ZEGOCLOUD/zego_uikit_prebuilt_call_flutter#26]
Just FYI, awesome_notifications recently had a major update to fix a critical error. I think it's worth taking a look at the updated version.

**Comment by lumberjack-programmer** [comment]
My Flutter IOS build fails. I guess, awesome_notifications package packages needs to get updated

Swift Compiler Error (Xcode): Type 'Logger' has no member 'd'
/.pub-cache/hosted/pub.dev/awesome_notifications-0.7.7/ios/Classes/lib/SwiftAwesomeNotificationsPlugin.swift:59:19
Swift Compiler Error (Xcode): Type 'Logger' has no member 'd'
/.pub-cache/hosted/pub.dev/awesome_notifications-0.7.7/ios/Classes/lib/SwiftAwesomeNotificationsPlugin.swift:60:19
...

**Comment by yoer** [comment]
Please use v3.15.6 version as we have removed 'awesome_notifications' and will no longer rely on it.

**Comment by yoer** [comment]
@moesaid @lumberjack-programmer
