### ISSUE TITLE
zego_uikit_prebuilt_call: ^3.15.5: [!] No podspec found for `flutter_callkit_incoming_yoer`

### ISSUE THREAD

**Issue by thanhnd2812** [ZEGOCLOUD/zego_uikit_prebuilt_call_flutter#27]
Hi there, 

I got this error after upgrading to 3.15.5

`[!] No podspec found for `flutter_callkit_incoming_yoer` in `.symlinks/plugins/flutter_callkit_incoming_yoer/ios``

Please help

**Comment by yoer** [comment]
fixed by v3.15.6
