### ISSUE TITLE
Not able to build the app after installation 

### ISSUE THREAD

**Issue by sauravdpl** [ZEGOCLOUD/zego_uikit_prebuilt_call_flutter#29]
I have integrated the Zegocloud video call using a prebuilt call SDK  but when I tried to build to build the app I got tons of error 
as followings:
 `../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/zego_uikit-2.14.0/lib/src/plugins/signaling/defines.dart:9:8: Error: Type 'ZegoSignalingPluginNotificationConfig' not found.
    on ZegoSignalingPluginNotificationConfig {
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/zego_uikit_signaling_plugin-2.6.3/lib/src/invitation.dart:12:5: Error: Type 'ZegoSignalingPluginNotificationConfig' not found.
    ZegoSignalingPluginNotificationConfig? notificationConfig,
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/zego_uikit-2.14.0/lib/src/plugins/signaling/impl/service/notification_service.dart:39:5: Error: Type 'ZegoSignalingPluginOutgoingNotificationConfig' not found.
    ZegoSignalingPluginOutgoingNotificationConfig config,
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/zego_uikit-2.14.0/lib/src/plugins/signaling/impl/service/notification_service.dart:45:5: Error: Type 'ZegoSignalingPluginOutgoingNotificationChannelConfig' not found.
    ZegoSignalingPluginOutgoingNotificationChannelConfig config,
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/zego_uikit-2.14.0/lib/src/plugins/signaling/impl/core/invitation_data.dart:155:5: Error: Type 'ZegoSignalingPluginNotificationConfig' not found.
    ZegoSignalingPluginNotificationConfig? notificationConfig,
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/zego_uikit-2.14.0/lib/src/plugins/signaling/impl/core/notification_data.dart:48:5: Error: Type 'ZegoSignalingPluginOutgoingNotificationConfig' not found.
    ZegoSignalingPluginOutgoingNotificationConfig config,
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/zego_uikit-2.14.0/lib/src/plugins/signaling/impl/core/notification_data.dart:54:5: Error: Type 'ZegoSignalingPluginOutgoingNotificationChannelConfig' not found.
    ZegoSignalingPluginOutgoingNotificationChannelConfig config,
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/zego_uikit_signaling_plugin-2.6.3/lib/src/invitation.dart:4:7: Error: The non-abstract class 'ZegoSignalingPluginInvitationAPIImpl' is missing implementations for these members:
 - ZegoSignalingPluginInvitationAPI.addInvitation
 - ZegoSignalingPluginInvitationAPI.endInvitation
 - ZegoSignalingPluginInvitationAPI.joinInvitation
 - ZegoSignalingPluginInvitationAPI.quitInvitation
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class ZegoSignalingPluginInvitationAPIImpl
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/zego_plugin_adapter-2.10.0/lib/src/signaling/part/invitation.dart:15:51: Context: 'ZegoSignalingPluginInvitationAPI.addInvitation' is defined here.
  Future<ZegoSignalingPluginSendInvitationResult> addInvitation({
                                                  ^^^^^^^^^^^^^
../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/zego_plugin_adapter-2.10.0/lib/src/signaling/part/invitation.dart:48:50: Context: 'ZegoSignalingPluginInvitationAPI.endInvitation' is defined here.
  Future<ZegoSignalingPluginEndInvitationResult> endInvitation({
                                                 ^^^^^^^^^^^^^
../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/zego_plugin_adapter-2.10.0/lib/src/signaling/part/invitation.dart:22:51: Context: 'ZegoSignalingPluginInvitationAPI.joinInvitation' is defined here.
  Future<ZegoSignalingPluginJoinInvitationResult> joinInvitation({
                                                  ^^^^^^^^^^^^^^
../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/zego_plugin_adapter-2.10.0/lib/src/signaling/part/invitation.dart:55:51: Context: 'ZegoSignalingPluginInvitationAPI.quitInvitation' is defined here.
  Future<ZegoSignalingPluginQuitInvitationResult> quitInvitation({
                                                  ^^^^^^^^^^^^^^
../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/zego_uikit_signaling_plugin-2.6.3/lib/src/invitation.dart:250:7: Error: The non-abstract class 'ZegoSignalingPluginInvitationEventImpl' is missing implementations for these members:
 - ZegoSignalingPluginInvitationEvent.getOutgoingInvitationEndedEventStream
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class ZegoSignalingPluginInvitationEventImpl
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/zego_plugin_adapter-2.10.0/lib/src/signaling/part/invitation.dart:86:7: Context: 'ZegoSignalingPluginInvitationEvent.getOutgoingInvitationEndedEventStream' is defined here.
      getOutgoingInvitationEndedEventStream();
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/zego_uikit_signaling_plugin-2.6.3/lib/zego_uikit_signaling_plugin.dart:37:7: Error: The non-abstract class 'ZegoUIKitSignalingPlugin' is missing implementations for these members:
 - ZegoSignalingPluginInvitationAPI.addInvitation
 - ZegoSignalingPluginInvitationAPI.endInvitation
 - ZegoSignalingPluginInvitationAPI.joinInvitation
 - ZegoSignalingPluginInvitationAPI.quitInvitation
 - ZegoSignalingPluginInvitationEvent.getOutgoingInvitationEndedEventStream
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class ZegoUIKitSignalingPlugin
      ^^^^^^^^^^^^^^^^^^^^^^^^
../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/zego_plugin_adapter-2.10.0/lib/src/signaling/part/invitation.dart:15:51: Context: 'ZegoSignalingPluginInvitationAPI.addInvitation' is defined here.
  Future<ZegoSignalingPluginSendInvitationResult> addInvitation({
                                                  ^^^^^^^^^^^^^
../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/zego_plugin_adapter-2.10.0/lib/src/signaling/part/invitation.dart:48:50: Context: 'ZegoSignalingPluginInvitationAPI.endInvitation' is defined here.
  Future<ZegoSignalingPluginEndInvitationResult> endInvitation({
                                                 ^^^^^^^^^^^^^
../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/zego_plugin_adapter-2.10.0/lib/src/signaling/part/invitation.dart:22:51: Context: 'ZegoSignalingPluginInvitationAPI.joinInvitation' is defined here.
  Future<ZegoSignalingPluginJoinInvitationResult> joinInvitation({
                                                  ^^^^^^^^^^^^^^
../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/zego_plugin_adapter-2.10.0/lib/src/signaling/part/invitation.dart:55:51: Context: 'ZegoSignalingPluginInvitationAPI.quitInvitation' is defined here.
  Future<ZegoSignalingPluginQuitInvitationResult> quitInvitation({
                                                  ^^^^^^^^^^^^^^
../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/zego_plugin_adapter-2.10.0/lib/src/signaling/part/invitation.dart:86:7: Context: 'ZegoSignalingPluginInvitationEvent.getOutgoingInvitationEndedEventStream' is defined here.
      getOutgoingInvitationEndedEventStream();
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/zego_uikit_signaling_plugin-2.6.3/lib/src/invitation.dart:8:51: Error: The method 'ZegoSignalingPluginInvitationAPIImpl.sendInvitation' has fewer named arguments than those of overridden method 'ZegoSignalingPluginInvitationAPI.sendInvitation'.
  Future<ZegoSignalingPluginSendInvitationResult> sendInvitation({
                                                  ^
../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/zego_plugin_adapter-2.10.0/lib/src/signaling/part/invitation.dart:6:51: Context: This is the overridden method ('sendInvitation').
  Future<ZegoSignalingPluginSendInvitationResult> sendInvitation({
                                                  ^
../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/zego_uikit_signaling_plugin-2.6.3/lib/src/invitation.dart:8:51: Error: The method 'ZegoSignalingPluginInvitationAPIImpl.sendInvitation' doesn't have the named parameter 'isAdvancedMode' of overridden method 'ZegoSignalingPluginInvitationAPI.sendInvitation'.
  Future<ZegoSignalingPluginSendInvitationResult> sendInvitation({
                                                  ^
../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/zego_plugin_adapter-2.10.0/lib/src/signaling/part/invitation.dart:6:51: Context: This is the overridden method ('sendInvitation').
  Future<ZegoSignalingPluginSendInvitationResult> sendInvitation({
                                                  ^
../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/zego_uikit_signaling_plugin-2.6.3/lib/zego_uikit_signaling_plugin.dart:37:7: Error: Class 'ZegoUIKitSignalingPlugin' inherits multiple members named 'ZegoSignalingPluginInvitationAPIImpl.sendInvitation' with incompatible signatures.
Try adding a declaration of 'ZegoSignalingPluginInvitationAPIImpl.sendInvitation' to 'ZegoUIKitSignalingPlugin'.
class ZegoUIKitSignalingPlugin
      ^^^^^^^^^^^^^^^^^^^^^^^^
../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/zego_uikit_signaling_plugin-2.6.3/lib/src/invitation.dart:8:51: Context: This is one of the overridden members.
  Future<ZegoSignalingPluginSendInvitationResult> sendInvitation({
                                                  ^^^^^^^^^^^^^^^^^...
../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/zego_plugin_adapter-2.10.0/lib/src/signaling/part/invitation.dart:6:51: Context: This is one of the overridden members.
  Future<ZegoSignalingPluginSendInvitationResult> sendInvitation({
                                                  ^^^^^^^^^^^^^^^^^...
../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/zego_uikit_prebuilt_call-3.10.4/lib/src/call.dart:402:13: Error: The setter 'smallViewMargin' isn't defined for the class 'ZegoLayoutPictureInPictureConfig'.
 - 'ZegoLayoutPictureInPictureConfig' is from 'package:zego_uikit/src/components/audio_video_container/layout_picture_in_picture.dart' ('../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/zego_uikit-2.14.0/lib/src/components/audio_video_container/layout_picture_in_picture.dart').
Try correcting the name to the name of an existing setter, or defining a setter or field named 'smallViewMargin'.
          ..smallViewMargin = EdgeInsets.only(
            ^^^^^^^^^^^^^^^
../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/zego_uikit_prebuilt_call-3.10.4/lib/src/internal/controller_p.dart:40:24: Error: Required named parameter 'inviterID' must be provided.
        .sendInvitation(
                       ^
../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/zego_uikit_signaling_plugin-2.6.3/lib/src/invitation.dart:12:5: Error: 'ZegoSignalingPluginNotificationConfig' isn't a type.
    ZegoSignalingPluginNotificationConfig? notificationConfig,
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/zego_uikit_signaling_plugin-2.6.3/lib/src/invitation.dart:50:56: Error: A value of type 'ZegoSignalingPluginCallUserState' can't be assigned to a variable of type 'int'.
 - 'ZegoSignalingPluginCallUserState' is from 'package:zego_plugin_adapter/src/signaling/enums.dart' ('../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/zego_plugin_adapter-2.10.0/lib/src/signaling/enums.dart').
                ZegoSignalingPluginCallUserState.values[element.state.index]
                                                       ^
../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/zego_uikit-2.14.0/lib/src/plugins/signaling/impl/service/invitation_plugin_service.dart:46:5: Error: 'ZegoSignalingPluginNotificationConfig' isn't a type.
    ZegoSignalingPluginNotificationConfig? pluginNotificationConfig;
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/zego_uikit-2.14.0/lib/src/plugins/signaling/impl/service/invitation_plugin_service.dart:51:34: Error: The method 'ZegoSignalingPluginNotificationConfig' isn't defined for the class 'ZegoPluginInvitationService'.
 - 'ZegoPluginInvitationService' is from 'package:zego_uikit/src/plugins/signaling/impl/service/invitation_plugin_service.dart' ('../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/zego_uikit-2.14.0/lib/src/plugins/signaling/impl/service/invitation_plugin_service.dart').
Try correcting the name to the name of an existing method, or defining a method named 'ZegoSignalingPluginNotificationConfig'.
      pluginNotificationConfig = ZegoSignalingPluginNotificationConfig(
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/zego_uikit-2.14.0/lib/src/plugins/signaling/impl/service/notification_service.dart:39:5: Error: 'ZegoSignalingPluginOutgoingNotificationConfig' isn't a type.
    ZegoSignalingPluginOutgoingNotificationConfig config,
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/zego_uikit-2.14.0/lib/src/plugins/signaling/impl/service/notification_service.dart:45:5: Error: 'ZegoSignalingPluginOutgoingNotificationChannelConfig' isn't a type.
    ZegoSignalingPluginOutgoingNotificationChannelConfig config,
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/zego_uikit_signaling_plugin-2.6.3/lib/src/internal/event_center.dart:267:59: Error: Required named parameter 'mode' must be provided.
        ZegoSignalingPluginIncomingInvitationReceivedEvent(
                                                          ^
../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/zego_plugin_adapter-2.10.0/lib/src/signaling/defines.dart:424:9: Context: Found this candidate, but the arguments don't match.
  const ZegoSignalingPluginIncomingInvitationReceivedEvent({
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/zego_uikit_signaling_plugin-2.6.3/lib/src/internal/event_center.dart:293:60: Error: Required named parameter 'mode' must be provided.
        ZegoSignalingPluginIncomingInvitationCancelledEvent(
                                                           ^
../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/zego_plugin_adapter-2.10.0/lib/src/signaling/defines.dart:481:9: Context: Found this candidate, but the arguments don't match.
  const ZegoSignalingPluginIncomingInvitationCancelledEvent({
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/zego_uikit_signaling_plugin-2.6.3/lib/src/internal/event_center.dart:390:59: Error: Required named parameter 'invitationID' must be provided.
        ZegoSignalingPluginInvitationUserStateChangedEvent(
                                                          ^
../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/zego_plugin_adapter-2.10.0/lib/src/signaling/defines.dart:582:3: Context: Found this candidate, but the arguments don't match.
  ZegoSignalingPluginInvitationUserStateChangedEvent({
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/zego_uikit_signaling_plugin-2.6.3/lib/src/internal/event_center.dart:418:58: Error: Required named parameter 'mode' must be provided.
        ZegoSignalingPluginIncomingInvitationTimeoutEvent(
                                                         ^
../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/zego_plugin_adapter-2.10.0/lib/src/signaling/defines.dart:617:9: Context: Found this candidate, but the arguments don't match.
  const ZegoSignalingPluginIncomingInvitationTimeoutEvent({
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/zego_uikit-2.14.0/lib/src/plugins/signaling/impl/core/data.dart:104:42: Error: The method 'activeAudioByCallKit' isn't defined for the class 'ZegoSignalingPluginInterface'.
 - 'ZegoSignalingPluginInterface' is from 'package:zego_plugin_adapter/src/signaling/interface.dart' ('../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/zego_plugin_adapter-2.10.0/lib/src/signaling/interface.dart').
Try correcting the name to the name of an existing method, or defining a method named 'activeAudioByCallKit'.
    ZegoPluginAdapter().signalingPlugin!.activeAudioByCallKit();
                                         ^^^^^^^^^^^^^^^^^^^^
../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/zego_uikit-2.14.0/lib/src/plugins/signaling/impl/core/data.dart:117:49: Error: The method 'checkAppRunning' isn't defined for the class 'ZegoSignalingPluginInterface'.
 - 'ZegoSignalingPluginInterface' is from 'package:zego_plugin_adapter/src/signaling/interface.dart' ('../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/zego_plugin_adapter-2.10.0/lib/src/signaling/interface.dart').
Try correcting the name to the name of an existing method, or defining a method named 'checkAppRunning'.
    return ZegoPluginAdapter().signalingPlugin!.checkAppRunning();
                                                ^^^^^^^^^^^^^^^
../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/zego_uikit-2.14.0/lib/src/plugins/signaling/impl/core/invitation_data.dart:155:5: Error: 'ZegoSignalingPluginNotificationConfig' isn't a type.
    ZegoSignalingPluginNotificationConfig? notificationConfig,
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/zego_uikit-2.14.0/lib/src/plugins/signaling/impl/core/invitation_data.dart:163:11: Error: No named parameter with the name 'notificationConfig'.
          notificationConfig: notificationConfig,
          ^^^^^^^^^^^^^^^^^^
../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/zego_uikit-2.14.0/lib/src/plugins/signaling/impl/core/notification_data.dart:48:5: Error: 'ZegoSignalingPluginOutgoingNotificationConfig' isn't a type.
    ZegoSignalingPluginOutgoingNotificationConfig config,
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/zego_uikit-2.14.0/lib/src/plugins/signaling/impl/core/notification_data.dart:50:49: Error: The method 'addLocalNotification' isn't defined for the class 'ZegoSignalingPluginInterface'.
 - 'ZegoSignalingPluginInterface' is from 'package:zego_plugin_adapter/src/signaling/interface.dart' ('../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/zego_plugin_adapter-2.10.0/lib/src/signaling/interface.dart').
Try correcting the name to the name of an existing method, or defining a method named 'addLocalNotification'.
    return ZegoPluginAdapter().signalingPlugin!.addLocalNotification(config);
                                                ^^^^^^^^^^^^^^^^^^^^
../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/zego_uikit-2.14.0/lib/src/plugins/signaling/impl/core/notification_data.dart:54:5: Error: 'ZegoSignalingPluginOutgoingNotificationChannelConfig' isn't a type.
    ZegoSignalingPluginOutgoingNotificationChannelConfig config,
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/zego_uikit-2.14.0/lib/src/plugins/signaling/impl/core/notification_data.dart:58:10: Error: The method 'createNotificationChannel' isn't defined for the class 'ZegoSignalingPluginInterface'.
 - 'ZegoSignalingPluginInterface' is from 'package:zego_plugin_adapter/src/signaling/interface.dart' ('../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/zego_plugin_adapter-2.10.0/lib/src/signaling/interface.dart').
Try correcting the name to the name of an existing method, or defining a method named 'createNotificationChannel'.
        .createNotificationChannel(config);
         ^^^^^^^^^^^^^^^^^^^^^^^^^
../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/zego_uikit-2.14.0/lib/src/plugins/signaling/impl/core/notification_data.dart:62:49: Error: The method 'dismissAllNotifications' isn't defined for the class 'ZegoSignalingPluginInterface'.
 - 'ZegoSignalingPluginInterface' is from 'package:zego_plugin_adapter/src/signaling/interface.dart' ('../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/zego_plugin_adapter-2.10.0/lib/src/signaling/interface.dart').
Try correcting the name to the name of an existing method, or defining a method named 'dismissAllNotifications'.
    return ZegoPluginAdapter().signalingPlugin!.dismissAllNotifications();
                                                ^^^^^^^^^^^^^^^^^^^^^^^
../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/zego_uikit-2.14.0/lib/src/plugins/signaling/impl/core/notification_data.dart:66:49: Error: The method 'activeAppToForeground' isn't defined for the class 'ZegoSignalingPluginInterface'.
 - 'ZegoSignalingPluginInterface' is from 'package:zego_plugin_adapter/src/signaling/interface.dart' ('../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/zego_plugin_adapter-2.10.0/lib/src/signaling/interface.dart').
Try correcting the name to the name of an existing method, or defining a method named 'activeAppToForeground'.
    return ZegoPluginAdapter().signalingPlugin!.activeAppToForeground();
                                                ^^^^^^^^^^^^^^^^^^^^^
../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/zego_uikit-2.14.0/lib/src/plugins/signaling/impl/core/notification_data.dart:70:49: Error: The method 'requestDismissKeyguard' isn't defined for the class 'ZegoSignalingPluginInterface'.
 - 'ZegoSignalingPluginInterface' is from 'package:zego_plugin_adapter/src/signaling/interface.dart' ('../../AppData/Local/Pub/Cache/hosted/pub.dartlang.org/zego_plugin_adapter-2.10.0/lib/src/signaling/interface.dart').
Try correcting the name to the name of an existing method, or defining a method named 'requestDismissKeyguard'.
    return ZegoPluginAdapter().signalingPlugin!.requestDismissKeyguard();
                                                ^^^^^^^^^^^^^^^^^^^^^^

FAILURE: Build failed with an exception.

* Where:
Script 'C:\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 1159

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 13s
Exception: Gradle task assembleDebug failed with exit code 1
`

**Comment by AungYeZawDev** [comment]
me too, please let me know if any solution.

**Comment by AyeshaIftikhar** [comment]
Same issue here. Let me know if anyone find any solution

**Comment by yoer** [comment]
Please upgrade all the dependencies to the latest version.

  zego_uikit: ^2.17.3
  zego_uikit_prebuilt_call: ^4.1.3
  zego_uikit_signaling_plugin: ^2.7.3

**Comment by yoer** [comment]
if upgrade zego_uikit_prebuilt_call from 3.x version, [this document](https://pub.dev/documentation/zego_uikit_prebuilt_call/latest/topics/Migration:%20from%203.x%20to%204.0-topic.html) may help.

**Comment by yoer** [comment]
the issue has been too long without a reply, so it is closed.

**Comment by yoer** [comment]
please try `flutter clean` in your project folder path.
if not working after clean, you can try this:
``` dart
flutter pub cache repair
flutter pub get
```

**Comment by yoer** [comment]
anyone working? @DhruvamUnikon @AyeshaIftikhar @AungYeZawDev @sauravdpl

**Comment by AungYeZawDev** [comment]
In my project flutter version Flutter 3.7.12 Dart 2.19.6 work with 
zego_uikit: ^2.7.6
zego_uikit_prebuilt_call: ^3.10.5
zego_uikit_signaling_plugin: ^2.2.0

**Comment by yoer** [comment]
> In my project flutter version Flutter 3.7.12 Dart 2.19.6 work with zego_uikit: ^2.7.6 zego_uikit_prebuilt_call: ^3.10.5 zego_uikit_signaling_plugin: ^2.2.0

May I ask what version is `zego_express_engine` in `pubspec.lock`?

**Comment by AungYeZawDev** [comment]
zego_express_engine:
    dependency: transitive
    description:
      name: zego_express_engine
      sha256: "86354c4c83e6b792bdc09ec79815e5c6c1ff61a2e5380f60a8b7db6ebe6553f1"
      url: "https://pub.dev"
    source: hosted
    version: "3.16.0"

**Comment by AungYeZawDev** [comment]
zego_express_engine:
    dependency: transitive
    description:
      name: zego_express_engine
      sha256: "....."
      url: "https://pub.dev"
    source: hosted
    version: "3.16.0"
