### ISSUE TITLE
onOnlySelfInRoom callback is not working when the user is alone in the room

### ISSUE THREAD

**Issue by navidanchitrali** [ZEGOCLOUD/zego_uikit_prebuilt_call_flutter#3]
i am trying with this code

          config: ZegoUIKitPrebuiltCallConfig.oneOnOneVideoCall()
            ..onOnlySelfInRoom = (context) async {
              await Future.delayed(Duration(seconds: 10));
              Navigator.pop(context);
            },

I want to exit from the room  after a few seconds when the user is alone in the one-o-one video calling room, but onOnlySelfInRoom function is not working for this

**Comment by navidanchitrali** [comment]
@yoer

**Comment by yoer** [comment]
![image](https://user-images.githubusercontent.com/11307627/222367299-9758970c-b124-4c3b-b3e2-7553fcb2d51d.png)

**Comment by yoer** [comment]
no reply, temporarily closed.
If you're still having trouble, please describe in detail the configuration and context you're using
