### ISSUE TITLE
not building for ios 

### ISSUE THREAD

**Issue by mush123** [ZEGOCLOUD/zego_uikit_prebuilt_call_flutter#32]
I am getting following error 

 2024-02-02 17:11:49.651 xcodebuild[22970:164684] [MT] DVTAssertions: Warning in /System/Volumes/Data/SWE/Apps/DT/BuildRoots/BuildRoot11/ActiveBuildRoot/Library/Caches/com.apple.xbs/Sources/IDEFrameworks/IDEFrameworks-22269/IDEFoundation/Provisioning/Capabilities Infrastructure/IDECapabilityQuerySelection.swift:103
    Details:  createItemModels creation requirements should not create capability item model for a capability item model that already exists.
    Function: createItemModels(for:itemModelSource:)
    Thread:   <_NSMainThread: 0x7fa487007e50>{number = 1, name = main}
    Please file a bug at https://feedbackassistant.apple.com with this warning message and any useful information you can provide.
    2024-02-02 17:11:49.651 xcodebuild[22970:164684] [MT] DVTAssertions: Warning in /System/Volumes/Data/SWE/Apps/DT/BuildRoots/BuildRoot11/ActiveBuildRoot/Library/Caches/com.apple.xbs/Sources/IDEFrameworks/IDEFrameworks-22269/IDEFoundation/Provisioning/Capabilities Infrastructure/IDECapabilityQuerySelection.swift:103
    Details:  createItemModels creation requirements should not create capability item model for a capability item model that already exists.
    Function: createItemModels(for:itemModelSource:)
    Thread:   <_NSMainThread: 0x7fa487007e50>{number = 1, name = main}
    Please file a bug at https://feedbackassistant.apple.com with this warning message and any useful information you can provide.
    ** BUILD FAILED **
2

Xcode's output:
↳
    Writing result bundle at path:
    	/var/folders/mz/4dc23t7n1kg_6r8rbq92ss540000gn/T/flutter_tools.WZTerA/flutter_ios_build_temp_dirgD6X9d/temporary_xcresult_bundle

    sh: /Users/vhslogitech/Desktop/SVN: No such file or directory
    Command PhaseScriptExecution failed with a nonzero exit code
    note: Run script build phase 'Run Script' will be run during every build because the option to run the script phase "Based on dependency analysis" is unchecked. (in target 'Runner' from project 'Runner')
    note: Run script build phase 'Thin Binary' will be run during every build because the option to run the script phase "Based on dependency analysis" is unchecked. (in target 'Runner' from project 'Runner')

Error launching application on iPhone.

**Comment by yoer** [comment]
Is this an error reported by running your own app? Or is it our demo?
Is the reported error related to zego_uikit_prebuilt_call_flutter?

**Comment by yoer** [comment]
this error seems to have no clue, have you tried **flutter clean** and rerun it?

**Comment by mush123** [comment]
Yes I did flutter clean. The above error comes when I add zego_uikit_prebuilt_call_flutter in my project. It works fine if I remove zego_uikit_prebuilt_call_flutter .

**Comment by yoer** [comment]
what's your project absolute path? does it contains space or special chars?

**Comment by yoer** [comment]
that's nothing `zego` things in the error message you provide, so it's a little bit hard to figure it out.

have you try run [call demo](https://github.com/ZEGOCLOUD/zego_uikit_prebuilt_call_example_flutter)?

**Comment by yoer** [comment]
[quick start](https://www.zegocloud.com/doc/callkit/Call%20Kit/main/Quick%20start/b26d509e) 
[Quick start (with call invitation)](https://www.zegocloud.com/doc/callkit/Call%20Kit/main/Quick%20start%20(with%20call%20invitation)/eb1d3c42)

let's try follow these docs, maybe can help..

**Comment by mush123** [comment]
Thanks dear. It worked .... the issue was in the project's absolute path. I had created the folder name with space and kept project inside it. I replaced the space with underscore and it worked.

**Comment by yoer** [comment]
mark

issue keyword: `Command PhaseScriptExecution failed with a nonzero exit code`

check project absolute path, does it contains space or special chars?
