### ISSUE TITLE
How to programmatically end a call?

### ISSUE THREAD

**Issue by han-tm** [ZEGOCLOUD/zego_uikit_prebuilt_call_flutter#33]
**Is your feature request related to a problem? Please describe.**
Is it possible to end a call programmatically? For example, I need to end the call after a certain amount of time

**Describe the solution you'd like**
It would be great to have a controller with basic functionality.

**Comment by yoer** [comment]
[APIs](https://pub.dev/documentation/zego_uikit_prebuilt_call/latest/topics/APIs-topic.html#zegouikitprebuiltcallcontrollerzego_uikit_prebuilt_callzegouikitprebuiltcallcontroller-classhtml)

[hangUp](https://pub.dev/documentation/zego_uikit_prebuilt_call/latest/topics/APIs-topic.html#hangup)

**Comment by yoer** [comment]
[onDurationUpdate](https://pub.dev/documentation/zego_uikit_prebuilt_call/latest/zego_uikit_prebuilt_call/ZegoCallDurationConfig/onDurationUpdate.html)

[demo](https://www.zegocloud.com/doc/callkit/Call%20Kit/main/Calling%20config/Calculate%20call%20duration/c75ba0e1)
