### ISSUE TITLE
after updating from 3.16 to 4.2.2 i am havingthis please help me fix

### ISSUE THREAD

**Issue by fisforfaheem** [ZEGOCLOUD/zego_uikit_prebuilt_call_flutter#35]
ZegoUIKitPrebuiltCall(
              appID: 2123453149,
              appSign:
                  'dsadasdasdasd',
              userID: AuthProvider.getUserDetails().email,
              userName: AuthProvider.getUserDetails().displayName,
              callID: model.channelNAme,
              config: ZegoUIKitPrebuiltCallConfig.oneOnOneVideoCall()
                ..onOnlySelfInRoom = (context) {
                  model.onDisconnect(context);
                }
                ..onHangUp = () => model.onDisconnect(context)

            
<img width="1088" alt="Screenshot 2024-03-12 at 5 05 04 PM" src="https://github.com/ZEGOCLOUD/zego_uikit_prebuilt_call_flutter/assets/35878088/e07e7639-7035-4b27-8fe9-c73c91e599b1">

**Comment by yoer** [comment]
https://pub.dev/documentation/zego_uikit_prebuilt_call/latest/topics/Migration_v4.x-topic.html#onhangupononlyselfinroomonmeremovedfromroom

You can refer to this migration guide, which has detailed migration steps.

**Comment by yoer** [comment]
```
ZegoUIKitPrebuiltCall(
    ...
    events: ZegoUIKitPrebuiltCallEvents(
      onCallEnd: (
          ZegoCallEndEvent event,

          /// defaultAction to return to the previous page
          VoidCallback defaultAction,
          ) {
        model.onDisconnect(context);
      },
    ),
  );
```

**Comment by fisforfaheem** [comment]
I can't understand that, kindly help me with this

**Comment by yoer** [comment]
move  your code in`onHangUp` and `onOnlySelfInRoom`  from `config` to `events` in ZegoUIKitPrebuiltCall

**Comment by yoer** [comment]
before:
```dart
 ZegoUIKitPrebuiltCall(
     ...
     config: ZegoUIKitPrebuiltCallConfig(
       onHangUp: () {
         model.onDisconnect(context);
       },
       onOnlySelfInRoom: () {
         model.onDisconnect(context);
       },
     ),
   );
```

after:

``` dart
 ZegoUIKitPrebuiltCall(
     ...
     events: ZegoUIKitPrebuiltCallEvents(
       onCallEnd: (
           ZegoCallEndEvent event,

           /// defaultAction to return to the previous page          VoidCallback defaultAction,
           ) {
         model.onDisconnect(context);
       },
     ),
   );
```

**Comment by fisforfaheem** [comment]
what about :  ..onOnlySelfInRoom = (context) {
                     model.onDisconnect(context);
                    }

and 

  ..onHangUp = () => model.onDisconnect(context)

                onDispose: () => model.onDisconnect(context),



currently i have done this only:   events: ZegoUIKitPrebuiltCallEvents(onCallEnd: (
              ZegoCallEndEvent event,

              /// defaultAction to return to the previous page
              VoidCallback defaultAction,
            ) {
                model.onDisconnect(context);
              debugPrint('onCallEnd, do whatever you want');

              /// you can call this defaultAction to return to the previous page,
              defaultAction.call();
            }

**Comment by fisforfaheem** [comment]
<img width="578" alt="image" src="https://github.com/ZEGOCLOUD/zego_uikit_prebuilt_call_flutter/assets/35878088/4e2cd0ce-1222-4768-be92-f280a9334658">

**Comment by fisforfaheem** [comment]
how to use this:     ..onOnlySelfInRoom = (context) {
                //         model.onDisconnect(context);
                //       }

**Comment by yoer** [comment]
- move **onOnlySelfInRoom** from `ZegoUIKitPrebuiltCallConfig`to ZegoUIKitPrebuiltCallEvents.**onCallEnd**(ZegoUIKitCallEndEvent(reason:ZegoUIKitCallEndReason.**remoteHangUp**), defaultAction)

``` dart
/// The default behavior is to return to the previous page.
///
/// If you override this callback, you must perform the page navigation
/// yourself to return to the previous page!!!
/// otherwise the user will remain on the current call page !!!!!
enum ZegoCallEndReason {
  /// the call ended due to a local hang-up
  localHangUp,

  /// the call ended when the remote user hung up, leaving only one local user in the call
  remoteHangUp,

  /// the call ended due to being kicked out
  kickOut,
}
```

when `event.reason` is `ZegoCallEndReason.remoteHangUp`, that's mean `onOnlySelfInRoom`

``` dart

ZegoUIKitPrebuiltCall(
  events: ZegoUIKitPrebuiltCallEvents(
    onCallEnd: (
      ZegoCallEndEvent event,

      /// defaultAction to return to the previous page
      VoidCallback defaultAction,
    ) {
      model.onDisconnect(context);

      defaultAction.call();

      switch (event.reason) {
        case ZegoCallEndReason.localHangUp:
          /// onHangUp
          break;
        case ZegoCallEndReason.remoteHangUp:
          /// onOnlySelfInRoom
          break;
        case ZegoCallEndReason.kickOut:
          /// onMeRemovedFromRoom
          break;
      }
    },
  ),
);
```
