### ISSUE TITLE
Zegocloud warning appstore

### ISSUE THREAD

**Issue by zaycode** [ZEGOCLOUD/zego_uikit_prebuilt_call_flutter#36]
please add documentation about this

Hello,
We noticed one or more issues with a recent submission for TestFlight review for the following app:
·

· Version 2.21.2
· Build 5
Although submission for TestFlight review was successful, you may want to correct the following issues in your next submission for TestFlight review. Once you've corrected the issues, upload a new binary to App Store Connect.
ITMS-91056: Invalid privacy manifest - The PrivacyInfo.xcprivacy file from the following path is invalid: "Frameworks/ZegoExpressEngine.framework/PrivacyInfo.xcprivacy". While no action is required at this time, starting May 1, 2024, when you upload a new app or app update, keys and values in your app's privacy manifest must be in a valid format. For more details about privacy manifest files, visit: https://developer.apple.com/ documentation/bundle resources/privacy_manifest_files.
-
ITMS-91053: Missing API declaration Your app's code in the "Runner" file references one or more APIs that require reasons, including the following API categories: NSPrivacyAccessedAPICategory FileTimestamp. While no action is required at this time, starting May 1, 2024, when you upload a new app or app update, you must include a NSPrivacyAccessedAPITypes array in your app's privacy manifest to provide approved reasons for these APIs used by your app's code. For more details about this policy, including a list of required reason APIs and approved reasons for usage, visit: https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/
describing_use_of_required_reason_api.
ITMS-91053: Missing API declaration - Your app's code in the "Runner" file references one or more APIs that require reasons, including the following API categories: NSPrivacyAccessedAPICategoryUserDefaults. While no action is required at this time, starting May 1, 2024, when you upload a new app or app update, you must include a NSPrivacyAccessedAPITypes array in your app's privacy manifest to provide approved reasons for these APIs used by your app's code. For more details about this policy, including a list of required reason APIs and approved reasons for usage, visit: https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/
describing_use_of_required_reason_api.
-
ITMS-91053: Missing API declaration Your app's code in the "Runner" file references one or more APIs that require reasons, including the following API categories: NSPrivacyAccessedAPICategorySystemBootTime. While no action is required at this time, starting May 1, 2024, when you upload a new app or app update, you must include a NSPrivacyAccessedAPITypes array in your app's privacy manifest to provide approved reasons for these APIs used by your app's code. For more details about this policy, including a list of required reason APIs and approved reasons for usage, visit: https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/
describing_use_of_required_reason_api.
-
ITMS-91053: Missing API declaration Your app's code in the "Runner" file references one or more APIs that require reasons, including the following API categories: NSPrivacyAccessedAPICategory DiskSpace. While no action is required at this time, starting May 1, 2024, when you upload a new app or app update, you must include a NSPrivacyAccessedAPITypes array in your app's privacy manifest to provide approved reasons for these APIs used by your app's code. For more details about this policy, including a list of required reason APIs and approved reasons for usage, visit: https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/
describing_use_of_required_reason_api.
Apple Developer Relations

**Comment by yoer** [comment]
As this is a functional part of other internal departments, we have already billed them for urgent repairs

**Comment by yoer** [comment]
We are urging the ZegoExpressEngine team to solve this problem

**Comment by yoer** [comment]
https://pub.dev/packages/zego_express_engine/versions

zego_express_engine v3.13.0 on 4.22 had sloved this issue
