### ISSUE TITLE
Cant run Zego plugins update -> Flutter IOS build error. Command PhaseScriptExecution failed with a nonzero exit code

### ISSUE THREAD

**Issue by cyber-pride** [ZEGOCLOUD/zego_uikit_prebuilt_call_flutter#39]
- [x] I have read the [Getting Started](https://www.zegocloud.com/doc/callkit/Call%20Kit/main/Quick%20start/b26d509e) and [Getting Started(with call invitation)](https://www.zegocloud.com/doc/callkit/Call%20Kit/main/Quick%20start%20(with%20call%20invitation)/eb1d3c42)
- [x] I have already searched for the same problem

## Environment

| Technology            | Version       |
|-----------------------| ------------- |
| Flutter version       |     3.19.2      |
| Plugin version        |    3.10.6           |
| Xcode version         |     15.0      |

## Description

**Expected behavior:** 
Build must be succeeded
**Current behavior:** 
zego_express_engine 1 issues: Command PhaseScriptExecution failed with a nonzero exit code

**Comment by yoer** [comment]
Please run pod install in ios folder twice, that's some problem in zego_express_engine

**Comment by yoer** [comment]
or check you project's path, don't use empty characters

**Comment by yoer** [comment]
no reply received for too long, closed

**Comment by Zohaib521321** [comment]
@cyber-pride did you solve the issue?
Because I am still facing this issue

**Comment by yoer** [comment]
plz try **run twice pod install in iOS folder**

**Comment by napplidevfr** [comment]
im facing this error too and still cant find any solution
