### ISSUE TITLE
android release app crash 

### ISSUE THREAD

**Issue by tuyenworldconnect** [ZEGOCLOUD/zego_uikit_prebuilt_call_flutter#4]
[log.txt](https://github.com/ZEGOCLOUD/zego_uikit_prebuilt_call_flutter/files/11218301/log.txt)
[log1.txt](https://github.com/ZEGOCLOUD/zego_uikit_prebuilt_call_flutter/files/11218302/log1.txt)

Crashing when opening the android release app, the log show that the class of zego express engine is not found.
Please support me in this issue.

**Comment by yoer** [comment]
[Prevent code obfuscation.](https://docs.zegocloud.com/article/14826)

To prevent obfuscation of the SDK public class names, do the following:

a. In your project's your_project > android > app folder, create a proguard-rules.pro file with the following content as shown below:

-keep class **.zego.**  { *; }
-keep class **.**.zego_zpns.** { *; }


b. Add the following config code to the release part of the your_project/android/app/build.gradle file.

proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'

**Comment by XainMuhammadKhan** [comment]
my app still crashes
