### ISSUE TITLE
Cannot invoke a non-'const'

### ISSUE THREAD

**Issue by saemappdevs** [ZEGOCLOUD/zego_uikit_prebuilt_call_flutter#40]
When I try to update the package from 
  zego_uikit_prebuilt_call: ^3.3.16 to ^4.7.3
  zego_uikit_signaling_plugin: ^2.1.5 to ^2.5.5
  
 I'm getting these errors when I try to run 
 
 /C:/Users/AppDevs/AppData/Local/Pub/Cache/hosted/pub.dev/zego_uikit_prebuilt_call-4.8.4/lib/src/invitation/notification/notification_ring.dart:39:12: Error: Cannot invoke a non-'const' constructor where a const expression is expected.
Try using a constructor or factory that is 'const'.
      iOS: AudioContextIOS(
           ^^^^^^^^^^^^^^^
/C:/Users/AppDevs/AppData/Local/Pub/Cache/hosted/pub.dev/zego_uikit_prebuilt_call-4.8.4/lib/src/invitation/notification/notification_ring.dart:38:26: Error: Cannot invoke a non-'const' constructor where a const expression is expected.
Try using a constructor or factory that is 'const'.
    const audioContext = AudioContext(
                         ^^^^^^^^^^^^
Target kernel_snapshot failed: Exception

FAILURE: Build failed with an exception.

* Where:
Script 'D:\flutter\flutter_windows_3.16.7-stable\flutter\packages\flutter_tools\gradle\src\main\groovy\flutter.groovy' line: 1419

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'D:\flutter\flutter_windows_3.16.7-stable\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 22s
Error: Gradle task assembleDebug failed with exit code 1

Would you please look into this and suggest me the possible solution

**Comment by yoer** [comment]
What version of your local `audioplayers` is (in the $projectRoot/pubspec.lock file)?

**Comment by yoer** [comment]
have you test `flutter pub upgrade`?

**Comment by saemappdevs** [comment]
after changing the dependency of   audioplayers: ^5.2.0 the project successfully run.
Thank you.
