### ISSUE TITLE
How can I remove black empty black spaces (on top and bottom

### ISSUE THREAD

**Issue by han-tm** [ZEGOCLOUD/zego_uikit_prebuilt_call_flutter#43]
- [x] I have read the [Getting Started](https://www.zegocloud.com/doc/callkit/Call%20Kit/main/Quick%20start/b26d509e) and [Getting Started(with call invitation)](https://www.zegocloud.com/doc/callkit/Call%20Kit/main/Quick%20start%20(with%20call%20invitation)/eb1d3c42)
- [x] I have already searched for the same problem

## Environment

| Technology            | Version       |
|-----------------------| ------------- |
| Flutter version       |      3.19.4         |
| Plugin version        |      4.9.0         |
| Android version       |    API 34           |
| iOS version           |               |
| macOS version         |               |
| Xcode version         |               |
| Google Chrome version |               |

Device information: 

## Description
How to remove empty spaces from top and bottom?
**Expected behavior:** 
Try everything, but can't remove 
**Current behavior:** 

## Steps to reproduce
Use basic configuration

## Images   
![photo_2024-05-08_16-36-24](https://github.com/ZEGOCLOUD/zego_uikit_prebuilt_call_flutter/assets/85815609/cdaaa95b-d323-46f5-b24d-7e34b6095d5a)

**Comment by suraj-yadav0** [comment]
Try Adding the transparent background color

**Comment by han-tm** [comment]
> Try Adding the transparent background color

I've already tried it. I think the video itself is not stretched to fill the entire screen

**Comment by yoer** [comment]
``` dart
config.audioVideoView.useVideoViewAspectFill = true
```

**Comment by yoer** [comment]
no reply received for too long, closed
