### ISSUE TITLE
When we press the call and end button the screen on both sides goes black.

### ISSUE THREAD

**Issue by itkrishna97** [ZEGOCLOUD/zego_uikit_prebuilt_call_flutter#47]
When we press the call and end button the scree
![Screenshot_20240608_210948](https://github.com/ZEGOCLOUD/zego_uikit_prebuilt_call_flutter/assets/115341471/05515f67-4205-4e5f-a4e5-2af0388acaef)
n on both sides goes black.

**Comment by yoer** [comment]
You may have popped two widgets?

**Comment by yoer** [comment]
No reply for too long

**Comment by kevin4dhd** [comment]
Any solution? The same thing happens to me, the steps are as follows:

1. iOS user B goes out of the app (background)
2. User A makes a call to user B
3. User b answers
4. Wait 5 seconds
5. User A hangs up
6. User B exits the call, the normal screen is displayed for 1 second and then the screen goes black

I have a theory that it is a pop that is being executed by mistake inside the library, the last thing I want is to burify the project to fix it, I will investigate where the error is

**Comment by yoer** [comment]
> Any solution? The same thing happens to me, the steps are as follows:
> 
> 1. iOS user B goes out of the app (background)
> 2. User A makes a call to user B
> 3. User b answers
> 4. Wait 5 seconds
> 5. User A hangs up
> 6. User B exits the call, the normal screen is displayed for 1 second and then the screen goes black
> 
> I have a theory that it is a pop that is being executed by mistake inside the library, the last thing I want is to burify the project to fix it, I will investigate where the error is

your pubsepc.lock

**Comment by kevin4dhd** [comment]
For now I have solved it like this:
/// background callkit call, not need to navigate
      try {
        if (Navigator.of(_pageManager!.callInvitationData.contextQuery!.call())
            .canPop()) {
          Navigator.of(_pageManager!.callInvitationData.contextQuery!.call())
              .pop();
        }
      } catch (e) {
        ZegoLoggerService.logError(
          'Navigator pop exception:$e, '
          'contextQuery:${_pageManager?.callInvitationData.contextQuery}',
          tag: 'call-invitation',
          subTag: 'call invitation service',
        );
      }

El error estaba en este archivo: 
https://github.com/kevin4dhd/zego_uikit_prebuilt_call_flutter/blob/master/lib/src/invitation/callkit/background_service.dart

But still, there is a problem, if for example I start on screen A, then I go to screen B, then I go to screen C (all with push Navigator) If I then repeat the steps on screen C, the double pop will be executed, returning me to screen B, which should not happen, I should still be on screen C.

For now at least this patch that I have put on it makes me not get the black screen, for now it is fixed for me, in the same way I would really appreciate it if you could find a better solution.
