### ISSUE TITLE
i getting null check operator used on a null value while building with latest version 

### ISSUE THREAD

**Issue by atulproject99** [ZEGOCLOUD/zego_uikit_prebuilt_call_flutter#49]
- [x] I have read the [Getting Started](https://www.zegocloud.com/doc/callkit/Call%20Kit/main/Quick%20start/b26d509e) and [Getting Started(with call invitation)](https://www.zegocloud.com/doc/callkit/Call%20Kit/main/Quick%20start%20(with%20call%20invitation)/eb1d3c42)
- [x] I have already searched for the same problem

## Environment

| Technology            | Version       |
|-----------------------| ------------- |
| Flutter version       |  3.22.2             |
| Plugin version        |  4.12.1             |
| Android version       |    13           |
| iOS version           |  17             |
| macOS version         |     -          |
| Xcode version         |       -        |
| Google Chrome version |       -        |

Device information: 

## Description

**Expected behavior:**  when click on submit button call screen will be show

**Current behavior:**  when click on submit button red screen showing with null check operator used on a null value.

## Github link - https://github.com/atulproject99/audio_call_app

**Comment by atulproject99** [comment]
ok let me update

**Comment by yoer** [comment]
still coding & test, not publish yet

**Comment by atulproject99** [comment]
Okay

**Comment by atulproject99** [comment]
ok let me check

**Comment by atulproject99** [comment]
Thanks . its working now

**Comment by atulproject99** [comment]
Fixed
