### ISSUE TITLE
Missed call reminders

### ISSUE THREAD

**Issue by codoffer** [ZEGOCLOUD/zego_uikit_prebuilt_call_flutter#52]
**Is your feature request related to a problem? Please describe.**

When the receiver gets a call and is not able to receive it, there is no indication of the missed call.

**Describe the solution you'd like**
Please send a notification for missed calls.

**Describe alternatives you've considered**
There should be a webhook or callback for missed calls

**Additional context**

**Comment by yoer** [comment]
Arranging..

**Comment by codoffer** [comment]
Getting an error with the help page

> The conversion of the article content encountered an exception and cannot be displayed.

**Comment by yoer** [comment]
help page is ready to publishing

**Comment by yoer** [comment]
![oneonone_missed_call](https://github.com/user-attachments/assets/5df0f527-bff7-453c-bc0c-b3563509f4b4)

**Comment by yoer** [comment]
# Missed Call

If you need the redial feature for missed calls,(when **enableReCall** is true.), the invitation feature will no longer be compatible with versions before v4.12.0. This means that invitations sent by users of versions before v4.12.0 will not be received by users of version 4.12.0 or later, and vice versa.

Therefore, when releasing the app, it is important to implement a force upgrade for users to avoid issues with call reception.

Of course, if this feature is not used (that is, when **enableReCall** is set to false), the above problem will not exist.


## Configurations 

- ZegoCallInvitationConfig

  - bool `endCallWhenInitiatorLeave`:

    >  whether the entire call should end when the initiator leaves the call(will causing other participants can't enter the call anymore).
    >
    >  Default value is false.
    >
    >  If set to false, other participants can enter the call after the initiator leaves.

- ZegoCallInvitationMissedCallConfig

  - bool `enabled`

      > whether to allow popup the missed notification
      >
      >  Default value is true.

  - bool `enableReCall`

      > whether to allow redial the missed when click notification
      >
      > Default value is true.
      >
      > Please note that if allowed, it will be incompatible with versions before v4.12.0,
      >
      > which means mutual invitations cannot be made between the old and new versions of zego_uikit_prebuilt_call.

  - String? `resourceID`

      > The [resource id] for notification which same as [Zego Console](https://console.zegocloud.com/)

  - String? Function()? `notificationTitle`

      > The title for the notification.

  - String? Function()? `notificationMessage`

      > The message for the notification.

  - int `timeoutSeconds`

      > The timeout duration in seconds for the redial invitation.

### How to disable missed call pop-up notifications

```dart 
  ZegoUIKitPrebuiltCallInvitationService().init(
    ...
    config: ZegoCallInvitationConfig(
      endCallWhenInitiatorLeave: true,
      missedCall: ZegoCallInvitationMissedCallConfig(
        enabled: false,
      ),
    ),
  );
```

### How to disable missed call redial

```dart 
  ZegoUIKitPrebuiltCallInvitationService().init(
    ...
    config: ZegoCallInvitationConfig(
      endCallWhenInitiatorLeave: true,
      missedCall: ZegoCallInvitationMissedCallConfig(
        enableReCall: false,
      ),
    ),
  );
```


## Events

- ZegoUIKitPrebuiltCallInvitationEvents

  - Future\<void\> Function( \
    String `callID`, \
    ZegoCallUser `caller`, \
    ZegoCallInvitationType `callType`, \
    List\<ZegoCallUser\> `callees`, \
    String `customData`, \
    /// defaultAction is redial the missed call \
    Future\<void\> Function() `defaultAction`, \
  )? `onIncomingMissedCallClicked` : 
  
      > This callback will be triggered to **callee** when callee click the missed call notification

  - Function()? `onIncomingMissedCallReCallFailed`: 
  
      > missed call redial failed
  
```dart
  ZegoUIKitPrebuiltCallInvitationService().init(
    ...
    invitationEvents: ZegoUIKitPrebuiltCallInvitationEvents(
      onIncomingMissedCallClicked: (
        String callID,
        ZegoCallUser caller,
        ZegoCallInvitationType callType,
        List<ZegoCallUser> callees,
        String customData,

        /// defaultAction is redial the missed call
        Future<void> Function() defaultAction,
      ) async {
        /// do some other logic

        await defaultAction.call();
      },
      onIncomingMissedCallReCallFailed: () {

      },
    ),
    ...
  );
```
