### ISSUE TITLE
ITMS-91056: Invalid privacy manifest - The PrivacyInfo.xcprivacy file from the following path is invalid: “Frameworks/ZegoExpressEngine.framework/PrivacyInfo.xcprivacy”. Keys and values in any privacy manifest must be in a valid format.

### ISSUE THREAD

**Issue by priya1-2** [ZEGOCLOUD/zego_uikit_prebuilt_call_flutter#53]
Missing an expected key: 'NSPrivacyCollectedDataTypes' Runner.app/Frameworks/ZegoExpressEngine.framework/PrivacyInfo.xcprivacy

**Comment by yoer** [comment]
Have you modified the local ZegoExpressEngine library? 
Delete the local library downloaded by flutter and try pub get again.
![image](https://github.com/ZEGOCLOUD/zego_uikit_prebuilt_call_flutter/assets/11307627/10789620-6d77-48ca-a432-de1016b9617f)

**Comment by priya1-2** [comment]
Hi sir ,
can you explain to me a little bit more from which folder I need to delete
this file?

Thanks & Regards
Priya Srivastav

**Comment by priya1-2** [comment]
Hi , i did all these steps but the issue still persists.

**Comment by yoer** [comment]
What is your Flutter version and ZegoExpressEngine version?

**Comment by priya1-2** [comment]
Flutter version - 3.10.0
zego_uikit: ^2.14.3
zego_uikit_prebuilt_call: ^3.17.2
zego_uikit_signaling_plugin: ^2.6.2

**Comment by yoer** [comment]
What is your ZegoExpressEngine version? check in pubspec.lock

**Comment by priya1-2** [comment]
ZegoExpressEngine version: "3.12.4"

**Comment by yoer** [comment]
The version of flutter must be 3.13.0 or above

**Comment by yoer** [comment]
Is it normal after upgrading the Flutter version?

**Comment by priya1-2** [comment]
As you said to upgrade flutter version, i have upgrade the flutter version from 3.10.0 to 3.22.2 , but the issue still persists.

**Comment by priya1-2** [comment]
Hi sir ,
Please provide the solution ?

**Comment by yoer** [comment]
how about upgrade zego_express_engine to 3.15.

**Comment by yoer** [comment]
> how about upgrade zego_express_engine to 3.15.

The zego_express_engine version should be greater than 3.13.2

**Comment by yoer** [comment]
It’s been too long without reply

**Comment by priya1-2** [comment]
The issue was resolved .

**Comment by ussmaan-hub** [comment]
what's the approach to solve this @priya1-2

**Comment by yoer** [comment]
> what's the approach to solve this @priya1-2

The zego_express_engine version should be greater than 3.13.2
