### ISSUE TITLE
Build Error due to isShowFullScreen property in callkit_incoming_wrapper.dart

### ISSUE THREAD

**Issue by kghSachin** [ZEGOCLOUD/zego_uikit_prebuilt_call_flutter#57]
- [x] I have read the [Getting Started](https://www.zegocloud.com/doc/callkit/Call%20Kit/main/Quick%20start/b26d509e) and [Getting Started(with call invitation)](https://www.zegocloud.com/doc/callkit/Call%20Kit/main/Quick%20start%20(with%20call%20invitation)/eb1d3c42)
- [x] I have already searched for the same problem

## Environment

| Technology            | Version       |
|-----------------------| ------------- |
| Flutter version       |       3.19.6        |
| Plugin version        |        4.14.3       |
| Android version       |      11         |
| iOS version           |               |
| macOS version         |               |
| Xcode version         |               |
| Google Chrome version |               |

Device information: 

## Description

**Expected behavior:** 
Run one on one video call smoothly.
**Current behavior:** 
zego_uikit_prebuilt_call-4.12.11/lib/src/invitation/callkit/callkit_incoming_wrapper.dart:105:7: Error: No named parameter with the name 'isShowFullScreen'.
      isShowFullScreen: isShowFullScreen,
      ^^^^^^^^^^^^^^^^

ZegoUIKitPrebuiltCall(
        appID: 1442264916,
        appSign:
            appSign,
        callID: callId,
        userID: "userId12${widget.id}",
        userName: "userName12${widget.id}",
        config: ZegoUIKitPrebuiltCallConfig.oneOnOneVideoCall());

**Comment by yoer** [comment]
plz run `flutter pub upgrade`

**Comment by yoer** [comment]
use `zego_uikit_prebuilt_call: ^4.14.3` instead
