### ISSUE TITLE
Could not find com.github.umair13adil:RxLogs:1.0.20 - flutter_logs

### ISSUE THREAD

**Issue by cyberorigami** [ZEGOCLOUD/zego_uikit_prebuilt_call_flutter#58]
Seems issue with flutter_logs.

1. New project: 
flutter create newproject

2. added dependecies: 
zego_uikit_prebuilt_call: ^4.15.4
zego_uikit_signaling_plugin: ^2.8.2

causing below error:
`FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.github.umair13adil:RxLogs:1.0.20.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/github/umair13adil/RxLogs/1.0.20/RxLogs-1.0.20.pom
       - https://repo.maven.apache.org/maven2/com/github/umair13adil/RxLogs/1.0.20/RxLogs-1.0.20.pom
       - https://storage.googleapis.com/download.flutter.io/com/github/umair13adil/RxLogs/1.0.20/RxLogs-1.0.20.pom
       - https://jcenter.bintray.com/com/github/umair13adil/RxLogs/1.0.20/RxLogs-1.0.20.pom
       - https://jitpack.io/com/github/umair13adil/RxLogs/1.0.20/RxLogs-1.0.20.pom
       - https://maven.google.com/com/github/umair13adil/RxLogs/1.0.20/RxLogs-1.0.20.pom
       - https://storage.zego.im/maven/com/github/umair13adil/RxLogs/1.0.20/RxLogs-1.0.20.pom
       - https://developer.huawei.com/repo/com/github/umair13adil/RxLogs/1.0.20/RxLogs-1.0.20.pom
       - https://maven.columbus.heytapmobi.com/repository/releases/com/github/umair13adil/RxLogs/1.0.20/RxLogs-1.0.20.pom
     Required by:
         project :app > project :flutter_logs`

**Comment by yoer** [comment]
![img_v2_e2c6e8f4-1d86-4e8b-9e3b-51e86e073dcg](https://github.com/user-attachments/assets/2c291e68-09a9-4c60-9bbf-2505b4792063)
Change these arrows, if the version is lower than this

**Comment by cyberorigami** [comment]
Still having same error...

**Comment by sabir-ullah** [comment]
@cyberorigami 
Solution is: first delete **pubspec.lock** file
then run **flutter clean**
then update the kotlin version to latest in **build.gradle**
then run **flutter pub get**

**Comment by cyberorigami** [comment]
To implement above error you just have to 1. flutter create exampleproject 2. add zego packages and it will show above error. Any other packages works perfectly fine.

**Comment by Naing-Linn-6802** [comment]
I also have the same. Can someone help me?

**Comment by Abubakarshaikh** [comment]
Go to flutter_log.
make sure follow these steps too:
https://github.com/ZEGOCLOUD/zego_uikit_prebuilt_call_flutter/issues/58#issuecomment-2327822587

Then,
- From Vs Code/Transitive Dependencies
- Update the to version `v1.0.18`
<img width="347" alt="Screenshot 2024-09-06 at 9 56 33 PM" src="https://github.com/user-attachments/assets/e019a583-e733-4cb3-a005-675739a8cfa0">
<img width="453" alt="Screenshot 2024-09-06 at 9 56 59 PM" src="https://github.com/user-attachments/assets/5d188c8d-a6a1-415e-85be-0ae4c7cee9d4">

**Comment by Abubakarshaikh** [comment]
> I also have the same. Can someone help me?

follow these steps:
https://github.com/ZEGOCLOUD/zego_uikit_prebuilt_call_flutter/issues/58#issuecomment-2334464901

**Comment by Abubakarshaikh** [comment]
> I also have the same. Can someone help me?

follow these steps:
https://github.com/ZEGOCLOUD/zego_uikit_prebuilt_call_flutter/issues/58#issuecomment-2334464901

**Comment by Abubakarshaikh** [comment]
> Still having same error...

follow these steps:
https://github.com/ZEGOCLOUD/zego_uikit_prebuilt_call_flutter/issues/58#issuecomment-2334464901

**Comment by Naing-Linn-6802** [comment]
> Go to flutter_logs (dependency). Make sure to follow these steps too: [#58 (comment)](https://github.com/ZEGOCLOUD/zego_uikit_prebuilt_call_flutter/issues/58#issuecomment-2327822587)
> 
> Then,
> 
> * From Vs Code/Transitive Dependencies
> * Update the to version `v1.0.18` (android/app/build.gradle)
> 
> <img alt="Screenshot 2024-09-06 at 9 56 33 PM" width="347" src="https://private-user-images.githubusercontent.com/55477515/365247817-e019a583-e733-4cb3-a005-675739a8cfa0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU2NDMxMjgsIm5iZiI6MTcyNTY0MjgyOCwicGF0aCI6Ii81NTQ3NzUxNS8zNjUyNDc4MTctZTAxOWE1ODMtZTczMy00Y2IzLWEwMDUtNjc1NzM5YThjZmEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA2VDE3MTM0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZjODVkNmU1MWZiOTVhZWQzNmIyNTU3NmI4NzYwM2M1NmZhMzdhMTk4YjUwNTdmN2I3NGM0NzhlNDU5NzFlMzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DDfwX3VA9h7wxUPdRhO9YCr7EdaU3rXmmTc0D8TRGxI"> <img alt="Screenshot 2024-09-06 at 9 56 59 PM" width="453" src="https://private-user-images.githubusercontent.com/55477515/365247840-5d188c8d-a6a1-415e-85be-0ae4c7cee9d4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU2NDMxMjgsIm5iZiI6MTcyNTY0MjgyOCwicGF0aCI6Ii81NTQ3NzUxNS8zNjUyNDc4NDAtNWQxODhjOGQtYTZhMS00MTVlLTg1YmUtMGFlNGM3Y2VlOWQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA2VDE3MTM0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJiNWI4YWEwY2U0YTEwNDVmYWQ0ZjUyMDliNjg4Yzg1NDdlODgxMGNlMWRmY2QzOGNmNjg0MjYwNTBiNTA3OTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NUoV2OuNgawE4fFb6Z0ucYsSWH1HtVOkSjuPgIq5qwQ"> <img alt="Screenshot 2024-09-06 at 10 03 13 PM" width="346" src="https://private-user-images.githubusercontent.com/55477515/365249568-5f1e8b6e-4e99-4bce-a0d7-f02cd6bd9568.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU2NDMxMjgsIm5iZiI6MTcyNTY0MjgyOCwicGF0aCI6Ii81NTQ3NzUxNS8zNjUyNDk1NjgtNWYxZThiNmUtNGU5OS00YmNlLWEwZDctZjAyY2Q2YmQ5NTY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA2VDE3MTM0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVkYzViMTQ1MWZjZTM0ZTA1YmNiNmMxZjMwMDFkMzk4NWE1M2Y4NDAyMmZhNzFiN2EzMzg5ZDQ5ZTk4ZjdjYWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GjfOn5KuMRMnq8jGbvj49cQA_yGHAAbyqskB7ffbo3o">

This fixed my errors. Thank you for sharing.

**Comment by cyberorigami** [comment]
Found a solution here ([link](https://kotlinlang.org/docs/gradle-configure-project.html?utm_campaign=gradle-jvm-toolchain&utm_medium=kgp&utm_source=warnings#gradle-java-toolchains-support)) 
you need to change `id "com.android.application" version "8.1.0"` to `id "com.android.application" version "8.1.0-alpha09"` but after that zego plugin wants lower version of jetbrains:
```
Execution failed for task ':flutter_callkit_incoming_yoer:compileDebugKotlin'.
> 'compileDebugJavaWithJavac' task (current target is 1.8) and 'compileDebugKotlin' task (current target is 17) jvm target compatibility should be set to the same Java version.
```
so I lowered `id "org.jetbrains.kotlin.android" version "1.8.22"` to `id "org.jetbrains.kotlin.android" version "1.7.10"` and everything works.

**Comment by yoer** [comment]
![image](https://github.com/user-attachments/assets/7f6ec7ed-59cd-47ad-8b90-2fd8e29e7099)

There are two solutions, details are as follows

solution:

1. android/app/build.gradle

[link](https://stackoverflow.com/questions/76167320/flutter-android-execution-failed-for-task-appcheckdebugduplicateclasses-for)

The solution for this issue is to add the kotlin-bom dependency to the dependencies section in build.gradle (App Level) like the following:

dependencies {
    ...

    // To fix the duplicate class issue
    implementation(platform("org.jetbrains.kotlin:kotlin-bom:1.8.0"))

}
For more info, checkout the solution source [here](https://gist.github.com/danielcshn/7aa57155d766d46c043fde015f054d40).

2. android/settings.gradle

 changed project Kotlin version to 1.8.22.

``` 
   id "org.jetbrains.kotlin.android" version "1.8.22" apply false
```
