### ISSUE TITLE
Some time i getting userid in name key insead of username why ?

### ISSUE THREAD

**Issue by atul-techbuilders** [ZEGOCLOUD/zego_uikit_prebuilt_call_flutter#59]
I have implement one to one audio call. But when any use inviting me on call then invite user name no showing instead userid is showing . what is reason behind of this issue?

**Comment by yoer** [comment]
Now on the invited side, the invitation pop-up box displays the user name.
I don't quite understand what you're confused about.

**Comment by yoer** [comment]
- inviter login info
![image](https://github.com/user-attachments/assets/9952a03c-af24-4fc0-a940-b7148958f20d)
- invitee's offline pop-up
![image](https://github.com/user-attachments/assets/92546b59-547a-4908-b7df-672a5fc55aa8)
- invitee's online pop-up
![image](https://github.com/user-attachments/assets/52c7da29-5865-48aa-b24e-f12df78bef9b)

**Comment by atul-techbuilders** [comment]
@yoer thanks its resolved now

**Comment by atul-techbuilders** [comment]
Done
