### ISSUE TITLE
Reject and accept api not wroking for invitee?

### ISSUE THREAD

**Issue by atulproject99** [ZEGOCLOUD/zego_uikit_prebuilt_call_flutter#61]
"I have customized layouts for outgoing and incoming calls. When I try to accept a call by calling the accept method, it’s not working. The reject method also isn't working from the invitee’s side. Please look into this and explain a bit more."

Let me know if i need further adjustments!

**Comment by yoer** [comment]
Is there any log output on the console?

**Comment by atulproject99** [comment]
i getting log only for accept call its showing like this acccept invitation but not any log for for reject incoming call

**Comment by yoer** [comment]
If it fails, there should be error related prompts on the console.

**Comment by yoer** [comment]
You can also contact our technical support to figure out this issue

**Comment by atul-techbuilders** [comment]
@yoer thanks its now working in latest version

**Comment by atulproject99** [comment]
@yoer Thanks its working now in latest version

**Comment by yoer** [comment]
Sorry it took so long to fix this.
