### ISSUE TITLE
How can get custom data in ui config ?

### ISSUE THREAD

**Issue by atul-techbuilders** [ZEGOCLOUD/zego_uikit_prebuilt_call_flutter#64]
Hey i have create custom call widget for incoming and outgoing call so i want get custom data to show respective avatar based on gender so how can i get in code .
` uiConfig: ZegoCallInvitationUIConfig(
          inviter: ZegoCallInvitationInviterUIConfig(
        pageBuilder: (context, info) {
          return CustomCallWidget(
            info: info,
            onHangup: () async {
              log('on Hangup ');
              await ZegoUIKitPrebuiltCallInvitationService().cancel(
                  callees: [ZegoCallUser.fromUIKit(info.invitees.first)]);
            },
          );
        },
      ), invitee:
              ZegoCallInvitationInviteeUIConfig(pageBuilder: (context, info) {
        return CustomCallWidget(
            info: info,
            onAccept: () async {
              log('accept call');
              await ZegoUIKitPrebuiltCallInvitationService().accept();
            },
            isOutgoingCall: false,
            onHangup: () async {
              log(' hangup for incoming call');
              await ZegoUIKitPrebuiltCallInvitationService().reject();
            });
      })),
`

**Comment by yoer** [comment]
next version will provide **custom data** with `info.customData` of xxBuilder in uiConfig

**Comment by yoer** [comment]
today will publish this version

**Comment by atulproject99** [comment]
Thanks and i am waiting @yoer
