### ISSUE TITLE
Can we handle hold on on going call when we get call from other app and accept that call?

### ISSUE THREAD

**Issue by atulproject99** [ZEGOCLOUD/zego_uikit_prebuilt_call_flutter#65]
- [x] I have read the [Getting Started](https://www.zegocloud.com/doc/callkit/Call%20Kit/main/Quick%20start/b26d509e) and [Getting Started(with call invitation)](https://www.zegocloud.com/doc/callkit/Call%20Kit/main/Quick%20start%20(with%20call%20invitation)/eb1d3c42)
- [x] I have already searched for the same problem

## Environment

| Technology            | Version       |
|-----------------------| ------------- |
| Flutter version       | Latest              |
| Plugin version        | Latest             |
| Android version       |               |
| iOS version           |               |
| macOS version         |               |
| Xcode version         |               |
| Google Chrome version |               |

Device information: 

## Description

**Expected behavior:** 
Call should be go on hold if i will busy on other call or voip call

**Current behavior:** 

Problem: When we receive another call from an app like WhatsApp while an active call is ongoing in our Flutter app, the issue arises where our app’s call is not placed on hold. Ideally, when we answer the WhatsApp call, our app’s ongoing call should be automatically placed on hold.
## Steps to reproduce

1. This
2. Than that
3. Then

**Comment by atulproject99** [comment]
Problem: When we receive another call from an app like WhatsApp while an active call is ongoing in our Flutter app, the issue arises where our app’s call is not placed on hold. Ideally, when we answer the WhatsApp call, our app’s ongoing call should be automatically placed on hold.



https://github.com/user-attachments/assets/c378e950-76af-450d-ad78-3fcd2d276c3f
This the demo video, when we're in call and I got call on my mobile. App call is still running in background


https://github.com/user-attachments/assets/71b9b650-ee2d-43fe-8b8f-2eced29e0825

Demo video for WhatsApp call as well. It's allowing us to continue talking in this app as well and even on WhatsApp call as well.

**Comment by yoer** [comment]
You can try to listen to this event. When the phone microphone is interrupted, an event will be thrown.

```dart

ZegoUIKitPrebuiltCallInvitationService().init(
  ...
  events: ZegoUIKitPrebuiltCallEvents(
    audioVideo: ZegoCallAudioVideoEvents(
      onRemoteMicrophoneExceptionOccurred: (
        ZegoUIKitUser targetUser,
        ZegoUIKitDeviceExceptionType? type,
      ) {
        ///
      },
    ),
  ),
);
```

**Comment by atulproject99** [comment]
Ok i will test it

**Comment by atulproject99** [comment]
@yoer its working fine
