### ISSUE TITLE
Update these packages for support for flutter 3.10

### ISSUE THREAD

**Issue by fisforfaheem** [ZEGOCLOUD/zego_uikit_prebuilt_call_flutter#7]
zego_uikit: ^2.5.3
  zego_plugin_adapter: ^2.2.1
  zego_zpns: 2.3.2

  http: ^0.13.4
  flutter_vibrate: ^1.3.0
  audioplayers: ^1.0.1
  statemachine: ^3.2.0
  flutter_callkit_incoming: ^1.0.3+3
  uuid: ^3.0.7
  permission_handler: ^10.2.0

**Comment by yoer** [comment]
dart 3.10 had support now

**Comment by yoer** [comment]
please upgrade to these packages:
- zego_uikit_prebuilt_call: ^3.3.12
- zego_uikit: ^2.5.5
