### ISSUE TITLE
If phone is silent then it's not ringing, but if i open our app then call ring starts. 

### ISSUE THREAD

**Issue by atulproject99** [ZEGOCLOUD/zego_uikit_prebuilt_call_flutter#71]
- [x] I have read the [Getting Started](https://www.zegocloud.com/doc/callkit/Call%20Kit/main/Quick%20start/b26d509e) and [Getting Started(with call invitation)](https://www.zegocloud.com/doc/callkit/Call%20Kit/main/Quick%20start%20(with%20call%20invitation)/eb1d3c42)
- [x] I have already searched for the same problem

## Environment

| Technology            | Version       |
|-----------------------| ------------- |
| Flutter version       |Latest               |
| Plugin version        |     Latest          |
| Android version       |               |
| iOS version           |               |
| macOS version         |               |
| Xcode version         |   Latest            |
| Google Chrome version |               |

Device information: 

## Description

**Expected behavior:** 
if phone is on silent then it should not ringing whether app is open or not 
**Current behavior:** 
If phone is silent then it's not ringing, but if i open our app then call ring starts. 
## Steps to reproduce

1. This
2. Than that
3. Then

**Comment by yoer** [comment]
android or iOS? online or offline?

**Comment by atulproject99** [comment]
On both in both mode if phone is silent it should not be ring.

**Comment by yoer** [comment]
I just tested it and it is confirmed that this is the case under iOS. 
The ringing is from the earpiece, and the ringing also occurs when the sound is muted.
It should be some configuration about iOS under audio_players or there are bugs in audio_player? I'll take a look here.

**Comment by yoer** [comment]
zego_uikit_prebuilt_call: ^4.16.8

**Comment by atulproject99** [comment]
@yoer i have tested it on android 11 in online call  call is still ringing if phone is silent in offline its working fine please check
