### ISSUE TITLE
On call someone - 'package:zego_uikit_prebuilt_call/src/invitation/internal/internal_instance.dart': Failed assertion: line 21 pos 12: '_pageManager != null': pageManager is null, please call ZegoUIKitPrebuiltCallInvitationService().init(...) when user login

### ISSUE THREAD

**Issue by jitendravn** [ZEGOCLOUD/zego_uikit_prebuilt_call_flutter#73]
'package:zego_uikit_prebuilt_call/src/invitation/internal/internal_instance.dart': Failed assertion: line 21 pos 12: '_pageManager != null': pageManager is null, please call ZegoUIKitPrebuiltCallInvitationService().init(...) when user login

**Comment by yoer** [comment]
please call ZegoUIKitPrebuiltCallInvitationService().init(...) when user login

**Comment by jitendravn** [comment]
@yoer I already called this when user logged in 
Look at the code


void onUserLogin({User? user}) {
  print('on user login called');
  ZegoUIKitPrebuiltCallInvitationService().init(
    appID: int.parse(getEnv('ZEGO_APP_ID')) /*input your AppID*/,
    appSign: getEnv('ZEGO_APP_SIGN') /*input your AppSign*/,
   ...
   ...
  }

**Comment by yoer** [comment]
_pageManager has valued in ZegoUIKitPrebuiltCallInvitationService().init.

you can add breakpoint on package:zego_uikit_prebuilt_call/src/invitation/internal/internal_instance.dart line 21

**Comment by yoer** [comment]
1. if you use zim_kit package with prebuilt_call package, please make sure call `ZegoUIKitPrebuiltCallInvitationService().init` before `ZIMKit().connectUser`
