### ISSUE TITLE
PlatformException: InvocationTargetException - Null Object Reference in enableCamera Method for ZegoExpressEngine

### ISSUE THREAD

**Issue by aswanthdsrapha** [ZEGOCLOUD/zego_uikit_prebuilt_call_flutter#76]
## Environment

| Technology            | Version       |
|-----------------------| ------------- |
| Flutter version       |     3.24.4          |
| Plugin version        |    4.16.12           |
| Android version       |    14.0           |
| iOS version           |      -         |
| macOS version         |      -         |
| Xcode version         |        -       |
| Google Chrome version |       -        |

Device information: Samsung F15 5G

## Description

**Expected behavior:**  Should Enable Camera when enable camera button is pressed.

**Current behavior:** 
Throwing error:
`Unhandled Exception: PlatformException(InvocationTargetException, [enableCamera] Attempt to invoke virtual method 'void im.zego.zegoexpress.ZegoExpressEngine.enableCamera(boolean, im.zego.zegoexpress.constants.ZegoPublishChannel)' on a null object reference, null, null)
E/flutter (28411): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:648:7)
E/flutter (28411): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:334:18)
E/flutter (28411): <asynchronous suspension>
E/flutter (28411): #2      ZegoExpressImpl.enableCamera (package:zego_express_engine/src/impl/zego_express_impl.dart:1258:12)
E/flutter (28411): <asynchronous suspension>
E/flutter (28411): #3      ZegoExpressEngineDevice.enableCamera (package:zego_express_engine/src/zego_express_api_device.dart:278:12)
E/flutter (28411): <asynchronous suspension>
E/flutter (28411): #4      ZegoUIKitCore.turnOnLocalCamera (package:zego_uikit/src/services/internal/core/core.dart:881:5)
E/flutter (28411): <asynchronous suspension>
E/flutter (28411): `
## Steps to reproduce

```

class CallPage extends StatefulWidget {
  const CallPage({Key? key}) : super(key: key);

  @override
  State<StatefulWidget> createState() => CallPageState();
}

class CallPageState extends State<CallPage> {
  @override
  Widget build(BuildContext context) {
    return SafeArea(
      child: ZegoUIKitPrebuiltCall(
          appID: KeyCenter.instance.appID /*input your AppID*/,
          appSign: KeyCenter.instance.appSign /*input your AppSign*/,
          userID:
              "${Provider.of<ProfileViewModel>(context, listen: false).profile?.id}",
          userName:
              "${Provider.of<ProfileViewModel>(context, listen: false).profile?.firstName}",
          callID: 'call',
          config: ZegoUIKitPrebuiltCallConfig.oneOnOneVideoCall()

            /// support minimizing
            ..topMenuBar.isVisible = true
            ..topMenuBar.buttons = [
              ZegoCallMenuBarButtonName.minimizingButton,
              ZegoCallMenuBarButtonName.showMemberListButton,
              ZegoCallMenuBarButtonName.soundEffectButton,
            ]),
    );
  }
}
```
1. Open above page
2. Clicked on Camera Icon to enable camera.
3. Thrown this error.

**Comment by yoer** [comment]
Did you enter the wrong app ID or app sign?

**Comment by aswanthdsrapha** [comment]
> Did you enter the wrong app ID or app sign?

Yes sorry for late update i have given the appsign key wrong. Now its working we can close the case.
