### ISSUE TITLE
What went wrong: Execution failed for task ':flutter_callkit_incoming_yoer:compileReleaseKotlin'. Inconsistent JVM-target compatibility detected for tasks 'compileReleaseJavaWithJavac' (1.8) and 'compileReleaseKotlin' (21).

### ISSUE THREAD

**Issue by Amanullah4900** [ZEGOCLOUD/zego_uikit_prebuilt_call_flutter#79]
What went wrong: Execution failed for task ':flutter_callkit_incoming_yoer:compileReleaseKotlin'.
Inconsistent JVM-target compatibility detected for tasks 'compileReleaseJavaWithJavac' (1.8) and 'compileReleaseKotlin' (21).
<img width="743" alt="iVl9LHoj" src="https://github.com/user-attachments/assets/a304b5bb-8e81-4728-bf3f-7cb7d4a3d4b9">
<img width="730" alt="WkNCkxwX" src="https://github.com/user-attachments/assets/f72a4615-5277-4716-837a-7eb50ad5192e">
<img width="1051" alt="wiFJgHaY" src="https://github.com/user-attachments/assets/3830ec94-6cf2-4e45-8003-e88017806340">

**Comment by cyber-pride** [comment]
@yoer am also having this issue

**Comment by yoer** [comment]
> @yoer am also having this issue

Try upgrading [flutter_callkit_incoming_yoer](https://pub.dev/packages/flutter_callkit_incoming_yoer/versions/2.0.4+2) to 2.0.4+2 and see if it solves the problem.
@AhmadAbbas8

**Comment by yoer** [comment]
flutter_callkit_incoming_yoer: ^2.0.4+3

@Amanullah4900 @cyber-pride
