### ISSUE TITLE
Invitation ID issue

### ISSUE THREAD

**Issue by VimalNovelX** [ZEGOCLOUD/zego_uikit_prebuilt_call_flutter#82]
/C:/Users/91963/AppData/Local/Pub/Cache/hosted/pub.dev/zego_uikit-2.28.0-beta.3/lib/src/plugins/signaling/impl/service/invitation_service_advance.dart:233:55: Error: Required named parameter 'invitationID' must be provided.
      return ZegoSignalingPluginCancelInvitationResult(
                                                      ^

**Comment by yoer** [comment]
show me your pubspec.lock

**Comment by yoer** [comment]
Will be fixed today, please wait
