### ISSUE TITLE
My Flutter app is crashing when I log in using the Zegocloud prebuilt UI call kit.

### ISSUE THREAD

**Issue by AndreN10** [ZEGOCLOUD/zego_uikit_prebuilt_call_flutter#83]
```
ZegoUIKitPrebuiltCallInvitationService()
                      .init(
                    appID: int.parse(zegoAppId!),
                    appSign: zegoAppSign!,
                    userID: currentUserUid,
                    userName: currentUserUserName,
                    plugins: [
                      ZegoUIKitSignalingPlugin()
                    ],
                    notificationConfig:
                        ZegoCallInvitationNotificationConfig(
                      androidNotificationConfig:
                          ZegoCallAndroidNotificationConfig(
                        showFullScreen: true,
                        fullScreenBackground:
                            'assets/images/call.png',
                        channelID: 'ZegoUIKit',
                        channelName:
                            'Call Notifications',
                        sound: 'call',
                        icon: 'call',
                      ),
                      iOSNotificationConfig:
                          ZegoCallIOSNotificationConfig(
                        systemCallingIconName:
                            'CallKitIcon',
                      ),
                    ),
                    requireConfig:
                        (ZegoCallInvitationData
                            data) {
                      final config = (data
                                  .invitees.length >
                              1)
                          ? ZegoCallInvitationType
                                      .videoCall ==
                                  data.type
                              ? ZegoUIKitPrebuiltCallConfig
                                  .groupVideoCall()
                              : ZegoUIKitPrebuiltCallConfig
                                  .groupVoiceCall()
                          : ZegoCallInvitationType
                                      .videoCall ==
                                  data.type
                              ? ZegoUIKitPrebuiltCallConfig
                                  .oneOnOneVideoCall()
                              : ZegoUIKitPrebuiltCallConfig
                                  .oneOnOneVoiceCall();

                      config.topMenuBar.isVisible =
                          true;
                      config.topMenuBar.buttons.insert(
                          0,
                          ZegoCallMenuBarButtonName
                              .minimizingButton);

                      return config;
                    },
                  )
```

My app crashed when executing ZegoUIKitPrebuiltCallInvitationService().init

I have no idea why this happened.

Please help :(

And here's the log:

 

> I/PLogger (19183): {uikit-reporter}  {create}  {appID:214977202, params:{call_version: 4.16.16, user_id: B6Fdyx9w0JcUg8oURJPkUfbmh6M2}}  {18/12/2024 20:59:12}  {INFO}
>         I/PLogger (19183): {uikit-reporter}  {create}  {create}  {18/12/2024 20:59:12}  {INFO}
>         W/WindowOnBackDispatcher(19183): OnBackInvokedCallback is not enabled for the application.
>         W/WindowOnBackDispatcher(19183): Set 'android:enableOnBackInvokedCallback="true"' in the application manifest.
>         D/EGL_emulation(19183): app_time_stats: avg=123.85ms min=3.18ms max=1577.39ms count=20
>         I/ImeTracker(19183): com.test.testmobile:f45a17fe: onRequestHide at ORIGIN_CLIENT reason HIDE_SOFT_INPUT fromUser false
>         D/uikit plugin(19183): onMethodCall: reporterCreate
>         W/ee.testmobile(19183): Accessing hidden method Landroid/app/ActivityThread;->currentApplication()Landroid/app/Application; (unsupported, reflection, allowed)
>         D/nativeloader(19183): Load libZegoConnection.so using ns clns-7 from class loader (caller=/data/app/~~ZwmGEY-oUBfg47peSONgJA==/com.test.testmobile-4-gf4kNiORoKYZx4PezQSQ==/base.apk!classes7.dex): dlopen failed: library "libZegoConnection.so" not found
>         E/ZEGO    (19183): load ZegoConnection native library failed
>         E/ZEGO    (19183): java.lang.UnsatisfiedLinkError: dlopen failed: library "libZegoConnection.so" not found
>         E/ZEGO    (19183): 	at java.lang.Runtime.loadLibrary0(Runtime.java:1081)
>         E/ZEGO    (19183): 	at java.lang.Runtime.loadLibrary0(Runtime.java:1003)
>         E/ZEGO    (19183): 	at java.lang.System.loadLibrary(System.java:1765)
>         E/ZEGO    (19183): 	at im.zego.connection.internal.ZegoConnectionImpl.<clinit>(ZegoConnectionImpl.java:44)
>         E/ZEGO    (19183): 	at im.zego.connection.ZegoConnection.setLogFile(ZegoConnection.java:41)
>         E/ZEGO    (19183): 	at im.zego.uikit.libuikitreport.ZegoConnectionManager.init(ZegoConnectionManager.java:38)
>         E/ZEGO    (19183): 	at im.zego.uikit.libuikitreport.ReportUtil.create(ReportUtil.java:73)
>         E/ZEGO    (19183): 	at com.zegocloud.uikit.zego_uikit_plugin.ZegoUikitPlugin.onMethodCall(ZegoUikitPlugin.java:77)
>         E/ZEGO    (19183): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:267)
>         E/ZEGO    (19183): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:292)
>         E/ZEGO    (19183): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
>         E/ZEGO    (19183): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
>         E/ZEGO    (19183): 	at android.os.Handler.handleCallback(Handler.java:959)
>         E/ZEGO    (19183): 	at android.os.Handler.dispatchMessage(Handler.java:100)
>         E/ZEGO    (19183): 	at android.os.Looper.loopOnce(Looper.java:232)
>         E/ZEGO    (19183): 	at android.os.Looper.loop(Looper.java:317)
>         E/ZEGO    (19183): 	at android.app.ActivityThread.main(ActivityThread.java:8705)
>         E/ZEGO    (19183): 	at java.lang.reflect.Method.invoke(Native Method)
>         E/ZEGO    (19183): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
>         E/ZEGO    (19183): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:886)
>         E/ee.testmobile(19183): No implementation found for void im.zego.connection.internal.ZegoConnectionJniApi.setLogFile(java.lang.String) (tried Java_im_zego_connection_internal_ZegoConnectionJniApi_setLogFile and Java_im_zego_connection_internal_ZegoConnectionJniApi_setLogFile__Ljava_lang_String_2) - is the library loaded, e.g. System.loadLibrary?
>         E/AndroidRuntime(19183): FATAL EXCEPTION: main
>         E/AndroidRuntime(19183): Process: com.test.testmobile, PID: 19183
>         E/AndroidRuntime(19183): java.lang.UnsatisfiedLinkError: No implementation found for void im.zego.connection.internal.ZegoConnectionJniApi.setLogFile(java.lang.String) (tried Java_im_zego_connection_internal_ZegoConnectionJniApi_setLogFile and Java_im_zego_connection_internal_ZegoConnectionJniApi_setLogFile__Ljava_lang_String_2) - is the library loaded, e.g. System.loadLibrary?
>         E/AndroidRuntime(19183): 	at im.zego.connection.internal.ZegoConnectionJniApi.setLogFile(Native Method)
>         E/AndroidRuntime(19183): 	at im.zego.connection.internal.ZegoConnectionImpl.setLogFile(ZegoConnectionImpl.java:108)
>         E/AndroidRuntime(19183): 	at im.zego.connection.ZegoConnection.setLogFile(ZegoConnection.java:41)
>         E/AndroidRuntime(19183): 	at im.zego.uikit.libuikitreport.ZegoConnectionManager.init(ZegoConnectionManager.java:38)
>         E/AndroidRuntime(19183): 	at im.zego.uikit.libuikitreport.ReportUtil.create(ReportUtil.java:73)
>         E/AndroidRuntime(19183): 	at com.zegocloud.uikit.zego_uikit_plugin.ZegoUikitPlugin.onMethodCall(ZegoUikitPlugin.java:77)
>         E/AndroidRuntime(19183): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:267)
>         E/AndroidRuntime(19183): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:292)
>         E/AndroidRuntime(19183): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
>         E/AndroidRuntime(19183): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
>         E/AndroidRuntime(19183): 	at android.os.Handler.handleCallback(Handler.java:959)
>         E/AndroidRuntime(19183): 	at android.os.Handler.dispatchMessage(Handler.java:100)
>         E/AndroidRuntime(19183): 	at android.os.Looper.loopOnce(Looper.java:232)
>         E/AndroidRuntime(19183): 	at android.os.Looper.loop(Looper.java:317)
>         E/AndroidRuntime(19183): 	at android.app.ActivityThread.main(ActivityThread.java:8705)
>         E/AndroidRuntime(19183): 	at java.lang.reflect.Method.invoke(Native Method)
>         E/AndroidRuntime(19183): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
>         E/AndroidRuntime(19183): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:886)
>         I/Process (19183): Sending signal. PID: 19183 SIG: 9
>         Lost connection to device.
>         
>         Exited.

**Comment by yoer** [comment]
can you run **flutter doctor -v** and give me the information?

**Comment by yoer** [comment]
What version of android are you running?

**Comment by yoer** [comment]
We are very sorry. 

Someone reported this problem in the previous issue, but we cannot reproduce it, so please provide more detailed information to help us fix this problem.

If it has affected your development and launch, please try the old version first, **zego_uikit_prebuilt_call: 4.16.14**

**Comment by yoer** [comment]
Can you send me the apk or project source code? iamyoer@gmail.com

**Comment by yoer** [comment]
Are you running on a real machine or an emulator?

**Comment by yoer** [comment]
In build.gradle, what is your minSdkVersion set to?

**Comment by yoer** [comment]
@AndreN10

**Comment by AndreN10** [comment]
sorry for my late response

but here's my flutter docter -v result:

```
[√] Flutter (Channel stable, 3.24.3, on Microsoft Windows [Version 10.0.22631.4602], locale en-US)
    • Flutter version 3.24.3 on channel stable at C:\flutter\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2663184aa7 (3 months ago), 2024-09-11 16:27:48 -0500
    • Engine revision 36335019a8
    • Dart version 3.5.3
    • DevTools version 2.37.3

[√] Windows Version (Installed version of Windows is version 10 or higher)

[!] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at C:\Users\Andre\AppData\Local\Android\sdk
    • Platform android-35, build-tools 35.0.0
    X Android SDK file not found: C:\Users\Andre\AppData\Local\Android\sdk\platforms\android-35\android.jar.
    • Try re-installing or updating your Android SDK,
      visit https://flutter.dev/to/windows-android-setup for detailed instructions.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Enterprise 2022 17.11.5)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Enterprise
    • Visual Studio Enterprise 2022 version 17.11.35327.3
    • Windows 10 SDK version 10.0.22621.0

[!] Android Studio (version 2024.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    X Unable to determine bundled Java version.
    • Try updating or re-installing Android Studio.

[√] IntelliJ IDEA Ultimate Edition (version 2024.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2024.3
    • Flutter plugin version 83.0.4
    • Dart plugin version 243.22562.3

[√] VS Code (version 1.96.0)
    • VS Code at C:\Users\Andre\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.102.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22631.4602]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 131.0.6778.140
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 131.0.2903.99

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.
```

**Comment by AndreN10** [comment]
> Are you running on a real machine or an emulator?

I'm running in an emulator

**Comment by AndreN10** [comment]
> minSdkVersion

minSdkVersion 21
targetSdkVersion 34

**Comment by yoer** [comment]
> > Are you running on a real machine or an emulator?
> 
> I'm running in an emulator. It works well on the demo source, but when I integrate it into my main source, this happens.
> 
> Don't know, but my teammate managed to run the source; my guess is that the issue is related to the JVM.

Got it

**Comment by yoer** [comment]
try use **zego_uikit: ^2.27.19**

**Comment by yoer** [comment]
@AndreN10

**Comment by AndreN10** [comment]
No, actually I'm using:
- zego_uikit_signaling_plugin: ^2.8.2
- zego_uikit_prebuilt_call: ^4.13.1
@yoer
