### ISSUE TITLE
FAILURE: Build failed with an exception issues please fix them

### ISSUE THREAD

**Issue by fisforfaheem** [ZEGOCLOUD/zego_uikit_prebuilt_call_flutter#9]
4edoc@4EDocs-MacBook-Pro f4zone_2022 % flutter build appbundle --release        

Note: Recompile with -Xlint:deprecation for details.
Note: /Users/4edoc/.pub-cache/hosted/pub.dev/cloud_firestore-4.8.0/android/src/main/java/io/flutter/plugins/firebase/firestore/FlutterFirebaseFirestoreMessageCodec.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/4edoc/.pub-cache/hosted/pub.dev/zego_zpns-2.3.2+1/android/src/main/java/im/zego/zpns_flutter/internal/ZPNsPluginMethodHandler.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
e: file:///Users/4edoc/.pub-cache/hosted/pub.dev/flutter_callkit_incoming-2.0.0/android/src/main/kotlin/com/hiennv/flutter_callkit_incoming/CallkitIncomingActivity.kt:22:52 Unresolved reference: RippleRelativeLayout
e: file:///Users/4edoc/.pub-cache/hosted/pub.dev/flutter_callkit_incoming-2.0.0/android/src/main/kotlin/com/hiennv/flutter_callkit_incoming/CallkitIncomingActivity.kt:70:49 Unresolved reference: RippleRelativeLayout
e: file:///Users/4edoc/.pub-cache/hosted/pub.dev/flutter_callkit_incoming-2.0.0/android/src/main/kotlin/com/hiennv/flutter_callkit_incoming/CallkitIncomingActivity.kt:221:33 Not enough information to infer type variable T
e: file:///Users/4edoc/.pub-cache/hosted/pub.dev/flutter_callkit_incoming-2.0.0/android/src/main/kotlin/com/hiennv/flutter_callkit_incoming/CallkitIncomingActivity.kt:222:44 Variable expected
e: file:///Users/4edoc/.pub-cache/hosted/pub.dev/flutter_callkit_incoming-2.0.0/android/src/main/kotlin/com/hiennv/flutter_callkit_incoming/CallkitNotificationManager.kt:23:52 Unresolved reference: CircleTransform
e: file:///Users/4edoc/.pub-cache/hosted/pub.dev/flutter_callkit_incoming-2.0.0/android/src/main/kotlin/com/hiennv/flutter_callkit_incoming/CallkitNotificationManager.kt:220:28 Unresolved reference: CircleTransform
e: file:///Users/4edoc/.pub-cache/hosted/pub.dev/flutter_callkit_incoming-2.0.0/android/src/main/kotlin/com/hiennv/flutter_callkit_incoming/CallkitNotificationManager.kt:301:32 Unresolved reference: CircleTransform
Font asset "fa-regular-400.ttf" was tree-shaken, reducing it from 63728 to 1400 bytes (97.8% reduction). Tree-shaking can be disabled by providing the --no-tree-shake-icons flag when building your app.
Font asset "CupertinoIcons.ttf" was tree-shaken, reducing it from 283452 to 976 bytes (99.7% reduction). Tree-shaking can be disabled by providing the --no-tree-shake-icons flag when building your app.
Font asset "fa-solid-900.ttf" was tree-shaken, reducing it from 394832 to 2264 bytes (99.4% reduction). Tree-shaking can be disabled by providing the --no-tree-shake-icons flag when building your app.
Font asset "MaterialIcons-Regular.otf" was tree-shaken, reducing it from 1645184 to 4200 bytes (99.7% reduction). Tree-shaking can be disabled by providing the --no-tree-shake-icons flag when building your app.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':flutter_callkit_incoming:compileReleaseKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 7m 2s
Running Gradle task 'bundleRelease'...                            424.6s
Gradle task bundleRelease failed with exit code 1
4edoc@4EDocs-MacBook-Pro f4zone_2022 % flutter build appbundle --release

e: file:///Users/4edoc/.pub-cache/hosted/pub.dev/flutter_callkit_incoming-2.0.0/android/src/main/kotlin/com/hiennv/flutter_callkit_incoming/CallkitIncomingActivity.kt:22:52 Unresolved reference: RippleRelativeLayout
e: file:///Users/4edoc/.pub-cache/hosted/pub.dev/flutter_callkit_incoming-2.0.0/android/src/main/kotlin/com/hiennv/flutter_callkit_incoming/CallkitIncomingActivity.kt:70:49 Unresolved reference: RippleRelativeLayout
e: file:///Users/4edoc/.pub-cache/hosted/pub.dev/flutter_callkit_incoming-2.0.0/android/src/main/kotlin/com/hiennv/flutter_callkit_incoming/CallkitIncomingActivity.kt:221:33 Not enough information to infer type variable T
e: file:///Users/4edoc/.pub-cache/hosted/pub.dev/flutter_callkit_incoming-2.0.0/android/src/main/kotlin/com/hiennv/flutter_callkit_incoming/CallkitIncomingActivity.kt:222:44 Variable expected
e: file:///Users/4edoc/.pub-cache/hosted/pub.dev/flutter_callkit_incoming-2.0.0/android/src/main/kotlin/com/hiennv/flutter_callkit_incoming/CallkitNotificationManager.kt:23:52 Unresolved reference: CircleTransform
e: file:///Users/4edoc/.pub-cache/hosted/pub.dev/flutter_callkit_incoming-2.0.0/android/src/main/kotlin/com/hiennv/flutter_callkit_incoming/CallkitNotificationManager.kt:220:28 Unresolved reference: CircleTransform
e: file:///Users/4edoc/.pub-cache/hosted/pub.dev/flutter_callkit_incoming-2.0.0/android/src/main/kotlin/com/hiennv/flutter_callkit_incoming/CallkitNotificationManager.kt:301:32 Unresolved reference: CircleTransform
Font asset "fa-regular-400.ttf" was tree-shaken, reducing it from 63728 to 1400 bytes (97.8% reduction). Tree-shaking can be disabled by providing the --no-tree-shake-icons flag when building your app.
Font asset "CupertinoIcons.ttf" was tree-shaken, reducing it from 283452 to 976 bytes (99.7% reduction). Tree-shaking can be disabled by providing the --no-tree-shake-icons flag when building your app.
Font asset "fa-solid-900.ttf" was tree-shaken, reducing it from 394832 to 2264 bytes (99.4% reduction). Tree-shaking can be disabled by providing the --no-tree-shake-icons flag when building your app.
Font asset "MaterialIcons-Regular.otf" was tree-shaken, reducing it from 1645184 to 4200 bytes (99.7% reduction). Tree-shaking can be disabled by providing the --no-tree-shake-icons flag when building your app.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':flutter_callkit_incoming:compileReleaseKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4m 16s
Running Gradle task 'bundleRelease'...                            258.5s
Gradle task bundleRelease failed with exit code 1
4edoc@4EDocs-MacBook-Pro f4zone_2022 % flutter build appbundle --release

Font asset "fa-solid-900.ttf" was tree-shaken, reducing it from 394832 to 2264 bytes (99.4% reduction). Tree-shaking can be disabled by providing the --no-tree-shake-icons flag when building your app.
Font asset "fa-regular-400.ttf" was tree-shaken, reducing it from 63728 to 1400 bytes (97.8% reduction). Tree-shaking can be disabled by providing the --no-tree-shake-icons flag when building your app.
Font asset "CupertinoIcons.ttf" was tree-shaken, reducing it from 283452 to 976 bytes (99.7% reduction). Tree-shaking can be disabled by providing the --no-tree-shake-icons flag when building your app.
Font asset "MaterialIcons-Regular.otf" was tree-shaken, reducing it from 1645184 to 4200 bytes (99.7% reduction). Tree-shaking can be disabled by providing the --no-tree-shake-icons flag when building your app.
e: file:///Users/4edoc/.pub-cache/hosted/pub.dev/flutter_callkit_incoming-2.0.0/android/src/main/kotlin/com/hiennv/flutter_callkit_incoming/CallkitIncomingActivity.kt:22:52 Unresolved reference: RippleRelativeLayout
e: file:///Users/4edoc/.pub-cache/hosted/pub.dev/flutter_callkit_incoming-2.0.0/android/src/main/kotlin/com/hiennv/flutter_callkit_incoming/CallkitIncomingActivity.kt:70:49 Unresolved reference: RippleRelativeLayout
e: file:///Users/4edoc/.pub-cache/hosted/pub.dev/flutter_callkit_incoming-2.0.0/android/src/main/kotlin/com/hiennv/flutter_callkit_incoming/CallkitIncomingActivity.kt:221:33 Not enough information to infer type variable T
e: file:///Users/4edoc/.pub-cache/hosted/pub.dev/flutter_callkit_incoming-2.0.0/android/src/main/kotlin/com/hiennv/flutter_callkit_incoming/CallkitIncomingActivity.kt:222:44 Variable expected
e: file:///Users/4edoc/.pub-cache/hosted/pub.dev/flutter_callkit_incoming-2.0.0/android/src/main/kotlin/com/hiennv/flutter_callkit_incoming/CallkitNotificationManager.kt:23:52 Unresolved reference: CircleTransform
e: file:///Users/4edoc/.pub-cache/hosted/pub.dev/flutter_callkit_incoming-2.0.0/android/src/main/kotlin/com/hiennv/flutter_callkit_incoming/CallkitNotificationManager.kt:220:28 Unresolved reference: CircleTransform
e: file:///Users/4edoc/.pub-cache/hosted/pub.dev/flutter_callkit_incoming-2.0.0/android/src/main/kotlin/com/hiennv/flutter_callkit_incoming/CallkitNotificationManager.kt:301:32 Unresolved reference: CircleTransform

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':flutter_callkit_incoming:compileReleaseKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 57s
Running Gradle task 'bundleRelease'...                            118.9s
Gradle task bundleRelease failed with exit code 1
4edoc@4EDocs-MacBook-Pro f4zone_2022 %

**Comment by fisforfaheem** [comment]
buildscript {
ext.kotlin_version = '1.8.21'
repositories {
google()
mavenCentral()
}

dependencies {
classpath 'com.android.tools.build:gradle:7.4.2'
classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
// classpath 'com.google.gms:google-services:4.3.4'
classpath 'com.google.gms:google-services:4.3.15'
}
}

allprojects {
repositories {
google()
mavenCentral()
maven { url 'https://www.jitpack.io' }
}
}

rootProject.buildDir = '../build'
subprojects {
project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
project.evaluationDependsOn(':app')
}

tasks.register("clean", Delete) {
delete rootProject.buildDir
}


Okay Thanks, let me update



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
05/31/23,
07:17:43 PM

**Comment by fisforfaheem** [comment]
also i think i already have greater : #Thu May 11 21:17:17 PKT 2023
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
distributionUrl=https\://
services.gradle.org/distributions/gradle-7.6.1-all.zip
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
05/31/23,
07:18:46 PM

**Comment by yoer** [comment]
So now your problem still exists?

**Comment by fisforfaheem** [comment]
yes this is my current settings and problem still exists, Let me go back to
older version of zego...



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
05/31/23,
07:25:57 PM

**Comment by fisforfaheem** [comment]
I have used this version 3.3.16 of zegoclouduikit, and performed flutter clean and then a new build, now the issue is gone, But when I update the package to the latest version to benefit, it gives the above mentioned errors.

**Comment by yoer** [comment]
I can't run the kotlin 1.8.21 & gradle 7.6.1, but kotlin 1.8.0 & classpath gradle:4.1.0 & gradle 7.5 can

buildscript {
   // 1
    ext.kotlin_version = '1.8.0'
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        // 2
        classpath 'com.android.tools.build:gradle:4.1.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"

        // support notification
        classpath 'com.google.gms:google-services:4.3.10'
    }
}

// 3
distributionUrl=https\://services.gradle.org/distributions/gradle-7.5-all.zip

Can you run your project with this configuration?
 I'll do some research these days

**Comment by yoer** [comment]
ext.kotlin_version = '1.8.21'
classpath 'com.android.tools.build:gradle:4.1.3'
distributionUrl=https\://services.gradle.org/distributions/gradle-7.6.1-all.zip

change your classpath gradle from 7.4.2 to 4.1.3, it work
can work
